# Ejercicios sin resolución:

## Sobre capitulo I:

## Sobre capitulo II:

### :
&nbsp; Imagine que un mercado tiene las siguientes funciones de oferta y demanda laboral:


$$L^s = 10 + 10w \text{ y } L^d = 100 - 5w$$

a) Encuentre el nivel de equilibrio.

b) Suponga la fijacióon de un salario igual a 10. Determine que pasará con el equilibrio de mercado.

### :
 
&nbsp; En un país hay 1000 campos ganaderos competitivos, que producen carne y venden a \$2 el kg de carne. La función de producción de cada campo es:

$$q = 100L - L^2$$

&nbsp; Donde q son los kg de carne producidos diaramente y L el número de trabajadores en un campo.   \\ 
        
a) Calcule la demanda de trabajo de cada campo en función del salario (w).\\
b) Calcular demanda de trabajo del mercado.\\
c) Ahora considere que la oferta laboral del mercado está determinada por w = 25 + 0,003L. Encontrar el equilibrio del mercado de trabajo, cuantos trabajadores contrata cada campo y cuantos kg de carne producen.\\
d) Suponga ahora, que debido a la alta inmigración, la nueva función de oferta laboral de ese mercado es w = 10 + 0.003L. Encontrar el nuevo equilibrio del mercado laboral y explicar los efectos de la inmigración sobre el salario y empleo. Grafique.\\
e) Por último, considere que el gobierno fija un salario mínimo de \$95. Determine y grafique que sucede en ese mercado de trabajo. Ahora haga lo mismo pero con un salario mínimo de \$100.\\


### :

&nbsp; Sean las curvas de oferta y demanda de un bien X:
$$Q^{s} = 2000P - 2000 \text{ y } Q^{d} = 10000 - 2000P$$
&nbsp; Su producción genera una externalidad positiva tal que si se tuviera en cuenta la curva sería: 
$$Q^{s} = 2000P$$

a) Represente gráficamente la situación descrita indicando cuál sería el precio correspondiente a la asignación eficiente.

b) Calcule a cuánto asciende la externalidad positiva por unidad producida.


### :

&nbsp; Preguntas de concepto:

a) Ubique en un gráfico de oferta y demanda el peso muerto producido por un impuesto.

b) Explique, con apoyo de gráficos, cómo afecta la elasticidad de la oferta y de la demanda en el peso muerto producido por un impuesto.

c) Supongamos que el mercado de botellas de vino tiene las siguientes funciones de oferta y
demanda:

$$Q_o =-200+2P \quad y\quad Q_d=1400-\frac{2}{3}P$$

&nbsp; La cantidad y precio de equilibrio de mercado son $P^*=\$600$ y  $Q^*=1000$. Calcule el peso muerto producido por un impuesto de $400\frac{\$}{botella}$.


### :

&nbsp; Suponga el mercado de la carne de un país determinado por las siguientes funciones de oferta y demanda:

$$Q_o =-110+2P \quad y\quad Q_d=400-P$$

a) Calculé el precio y la cantidad óptima de mercado.

b) Ahora imagine que ese gobierno luego de varios estudios cree que es conveniente aplicar un subsidio de \$210, grafique y calcule que ocurriría en ese mercado.


## Sobre capitulo III:


### :

&nbsp; Supongamos que el mercado de bebidas tiene las siguientes funciones de oferta y demanda:

$$Q_d = 1400 - \frac{2P}{3}$$
$$Q_s = -200 +2P$$

&nbsp; Con P el precio $\frac{\$}{bebida}$. 

a) Calcule el precio y cantidad de equilibrio y grafique.

b) ¿Qué efecto tiene un impuesto de $\frac{\$400}{botella}$?

c) ¿Qué efecto tiene el impuesto en el bienestar social? ‚¿Qué efecto tiene ene l bienestar de los consumidores y productores? Hint: Calcule excedentes, ingreso fiscal y perdidas de peso muerto. 




### :

&nbsp; Suponga que existe un bien con las siguientes funciones de oferta y demanda $Q_d=6000-1000P$ y $Q_o=2000P$, respectivamente. Con las curvas indicadas anteriormente, resuelva:
a) Calcule el equilibrio de mercado.
b) Ahora suponga que el gobierno decide intervenir porque cree que el precio de equilibrio es muy alto, y decide bajarlo a la mitad ¿Qué debe hacer?
c) Si aplica un subsidio ¿De cuánto debe ser? ¿Se debe entregar a los productores o consumidores? 

### :

&nbsp; Imagine una función de demanda agregada $P=100-2Q$ y una función de oferta agregada $P=10+Q$ Computa el par $(p*,Q*)$ de equilibrio. El gobierno introdujo un impuesto de cuantía t sobre la función de demanda y calcule la nueva cantidad de equilibrio, el precio que recibe el productor y precio que paga el comprador $(Q_t;p_v;p_c)$. Realice el mismo ejercicio introduciendo el mismo impuesto sobre la oferta y calcula el nuevo $(Q_t;p_v;p_c)$. Demuestre que estas magnitudes son iguales en uno y otro caso.


### :

&nbsp; Imagine que el mercado del litio está dado por las siguientes funciones de oferta y demanda:
$$Q_o =4000+2000P \quad y\quad Q_d=160000-2000P$$

&nbsp; Pero ahora, para que sea posible la producción de ese litio, existe un costo marginal externo asociado a
su producción $CMgE = 0.2Q$.

a) Calcule precio y cantidad de equilibrio sin regulación.
b) Calcule precio y cantidad de equilibrio óptimos desde el punto de vista social.
c) Calcule el costo social de la solución en la parte a).
d) Estudie la opción de un impuesto para llegar al óptimo de la parte b).
e) Aplicado el nuevo impuesto, calcule los nuevos excedentes.


### :

&nbsp; El gobierno de un país quiere subsidiar con \$136 la compra de libros de economía, y para eso decide
aplicar un impuesto en el mercado del alcohol. Las funciones de demanda del mercado de los libros son:

$$Q_o =2P \quad y\quad Q_d=2400-6P$$

&nbsp; Y las funciones del mercado del alcohol son:

$$Q_o =P \quad y\quad Q_d=2000-P$$

&nbsp; ¿Cuál debe ser el monto del impuesto a aplicar sobre los alcoholes?


### :

&nbsp; Suponga que Wakanda es un país cerrado al comercio exterior (no existen importaciones ni exportaciones). En este, existe un mercado de textiles de acero con una función de oferta de $Q_o= 5P - 30$ y una función de demanda nacional de $Q_d=200-\frac{2P}{3}$. 

&nbsp; Luego, ocurre un cambio de mando y el nuevo presidente identifica que existe un precio mundial de textiles de acero de \$50. Debido a esto, decide abrir el mercado al exterior.  

a) Calcule el precio y cantidad de equilibrio antes de la apertura al exterior. Grafique y calcule los excedentes del consumidor, productor y total. 

b) Calcule el nuevo precio de equilibrio, calcule las diferencias en los excedentes del consumidor, productor y total. Graficar. 

c) ¿De donde proviene el aumento en el excedente del productor?  

d) ¿Tendría sentido aplicar un arancel en el mercado de textiles en Wakanda? 

e) ¿ Que sucedería en el caso de que el precio mundial fuera $P_{mundial}=30$? Calcule los nuevos excedentes. Grafique. 

f) Suponga que se le aplica un arancel de \$5 por unidad importada a los productores internacionales. Ubique los ingresos del gobierno y las perdidas de peso muerto en el gráfico.


### :

a) ¿Qué es el excedente del consumidor?

b) ¿Qué es el excedente del productor?

c) Un mercado tiene una curva de demanda igual a $P = 100 - 2Q_d$ y una función de oferta igual a $P = 20 + 2Q_0$. Grafique las curvas, el punto de equilibrio y calcule los excedentes del consumidor y productor.


## Sobre capitulo IV:


### :
&nbsp; Las curvas de demanda y de oferta del mercado del bien X vienen dadas por: $Q_d = 6000–1000P_x$$  $$Q_o = 2000P_x$.

El gobierno considera que el precio de equilibrio es demasiado alto y decide intervenir para reducirlo a la mitad. Tiene dos posibilidades: establecer un precio máximo o conceder a los productores una subvención por unidad vendida.

a) Calcule el precio y la cantidad intercambiada en el mercado sin intervención y con cada una de las dos medidos de intervención gubernamental. Represente las tres situaciones en un mismo gráfico.

b) Calcule el excedente del consumidor y productor cuando se impone la politica de precio máximo.

c) Calcule la cuantía de la subvención y la expresión matemática de la nueva curva de oferta.

d) Explique qué medida conviene más a los consumidores y qué medida conviene más a los productores(evalúe en términos de excedentes).

### :

&nbsp; En un mercado de helados existen los vendedores de vasos de helado y los consumidores de helado. El gobierno decide imponer un impuesto de \$0.50 a los vendedores de vasos de helado por cada vaso vendido.

a) ¿A qué curva afecta este impuesto, oferta o demanda?

b) ¿En qué sentido se desplaza la curva? ¿Por qué?

&nbsp; Ahora, asume un precio de equilibrio de mercado sin impuestos de \$3 por vaso de helado y una cantidad de equilibrio de 100 vasos de helado. Con el impuesto, ocurre que el nuevo precio de equilibrio es de \$3.30 y la cantidad de 90 vasos de helado.

c) Tomando en cuenta la información anterior, ¿cómo es la incidencia fiscal en este escenario? Grafique.

d) ¿Qué sucedería si el mismo impuesto se le aplicara a los consumidores en vez de a los vendedores? ¿Hacia dónde se desplaza la curva de demanda y por qué? ¿Cómo es la incidencia fiscal en este caso? Grafique.


### :
&nbsp; El mercado laboral de profesionales con capacidades tecnológicas se representa por la siguiente estructura de equilibrio entre oferta y demanda por precio P, de hora de trabajo (H):

$$P_d = 140 - \frac{H_d}{5} \text{ y } P_o = \frac{H_o}{5}+80$$
&nbsp; El Ministerio del Trabajo evalúa subsidiar capacitaciones tecnológicas para fomentar la oferta de trabajadores en este mercado. Se estima que el valor del subsidio a la oferta por hora de trabajo es igual a la mitad del componente no variable de la función inversa.

a) Calcule la cantidad de horas de equilibrio en el mercado con el subsidio.

b) Entregue los cálculos de equilibrio del ejercicio anterior, calcule y grafique los excedentes del consumidor y productor.

c) Calcule y grafique el costo en el que tiene que incurrir el estado para entregar este subsidio.


### :
&nbsp; Imagine que su vecino está formando una banda de rock y compra una batería y una guitarra eléctrica, pero quienes tocan la guitarra y batería no son buenos, por lo que practican todos los días al lado.
a) Mencione los costos privados y externos.
b) Apoyándose en un gráfico, explique por qué es una externalidad.
c) Analice y explique tres posibles soluciones.


### :
&nbsp; El mercado del papel en un país tiene las siguientes funciones oferta y demanda: $Q_d=162000-3000P$ y  $Q_0=37000+2000P$, donde $Q$ es la cantidad de papel en lotes y $P$ su precio. Hoy en día no se regula la contaminación que producen estas fábricas, causando estragos en la comunidad. El costo marginal externo asociado para este caso es $CMgE=0,001Q$.
a) Calcular precio y cantidad de equilibrio sin regulación de parte del gobierno.
b) Precio y cantidad óptima desde el punto de vista social.
- Calcule el costo social de la solución.
- Analice la alternativa de un impuesto y cuál sería su monto.
- Calcule los nuevos excedentes.


### :

&nbsp; Un grupo de pescadores de la X región se encuentra muy contento durantes estos últimos días. En los periódicos ha aparecido la noticia que el compuesto denominado “f” provoca un aceleramiento en el crecimiento de la anchoveta, un pez característico de la región. La buena nueva es que dicho compuesto es eliminado al mar por la compañía salmonera “Buen Salmón S.A.” al momento de realizar sus procesos de elaboración de salmón enlatado, lo cual ha traído como consecuencia un aumento del número de anchovetas pescadas durante las últimas semanas. Se ha realizado un estudio el cual ha estimado que el impacto positivo de la producción de salmones enlatados sobre la pesca de anchovetas está dada por $f(q) = \frac{bq^2}{4}$ donde “q” es la cantidad de latas producidas por “Buen Salmón SA”. La función de costos de la firma salmonera es $C(q) = a + bq^2$ y la demanda de mercado es $P(q) = a - cq$ Suponga competencia perfecta.

a) ¿Cuánto produce y a qué precio la firma salmonera?

b) El encargado de pesca del conglomerado de pescadores atribuye el aumento de la cantidad extraída de anchovetas a su excelente gestión, y en base a esto solicita al grupo un aumento de su sueldo. ¿Se merece el aumento el encargado? Argumente claramente su respuesta

c) ¿Cuál es el óptimo social de producción de la firma salmonera? Grafique y explique.


## Sobre capitulo V:

### :
&nbsp; Los siguiente tabla contiene los ingresos (en \%) de un país agrupados por quintiles.

 
::: {.content-visible when-format="html"}
```{=html}
<!DOCTYPE html>
<html>

<head>
    <style>
        table {
            font-family: Arial, sans-serif;
            border-collapse: collapse;
            width: 50%;
            margin: 20px;
        }

        th, td {
            border: 1px solid #dddddd;
            text-align: center;
            padding: 8px;
        }

        th {
            background-color: #f2f2f2;
        }
    </style>
</head>

<body>

    <table>
        <tr>
            <th>Quintil</th>
            <th>Ingreso (%)</th>
        </tr>
        <tr>
            <td>1</td>
            <td>7,7</td>
        </tr>
        <tr>
            <td>2</td>
            <td>12,3</td>
        </tr>
        <tr>
            <td>3</td>
            <td>15,48</td>
        </tr>
        <tr>
            <td>4</td>
            <td>20,5</td>
        </tr>
        <tr>
            <td>5</td>
            <td>44,1</td>
        </tr>
    </table>

</body>

</html>

```
:::

::: {.content-visible when-format="pdf"}
```{=tex}
\begin{table}[H]
\begin{tabular}{|c|c|}       
     \hline
    Quintil & Ingreso (\%) \\ \hline
     1  & 7,7  \\ \hline
     2  & 12,3 \\ \hline
     3  & 15,48 \\  \hline
     4  & 20,5 \\ \hline
     5  & 44,1 \\ \hline
    
\end{tabular}
\end{table}
```
:::

a) Grafique las líneas de equidad y desigualdad perfecta.
b) Graficar la curva de Lorenz.
c) Calcular coeficiente de Gini.


## Sobre capitulo VI:


### :
&nbsp; Imagine que un amigo le pide prestado \$80.000 y le devuelve \$95.000 a final de año. Suponga que la tasa de inflación ese año fue de 10\%.
a) Calcule la tasa de interés nominal que su amigo le pagaría.
b) Calcule la tasa de interés real que su amigo le pagaría.
c) Si su amigo se demora dos años en pagarle y mantiene la tasa de interés, ¿Cuánto recibiría usted?
d) Usted le presta el dinero a su amigo en UF, cuando vale \$30.000, si su amigo mantiene la tasa de interés real y el prestamo es por un año, ¿Cuánto dinero recibe?
e) Ahora suponga que su amigo le ofrece devolverle \$110.000 al finalizar el tercer año. ¿Conviene darle el préstamo?

### :

Como premio de lotería ha recibido \$100.000, dado que valora más el dinero mañana, ha decidido depositar su capital. El banco le ofrece las siguientes opciones por 4 años:
- Depositar los \$100.000 con una tasa anual efectiva del 12\%.
- Colocar los \$100.000 en un cuenta con interés efectiva trimestral del 3\%. 
&nbsp; ¿Qué opción le ocnviene más?

### :

&nbsp; Suponga que hace un año hizo un depósito de \$500.000 en una cuenta, justo un año después usted tiene \$750.000.
a) ¿Cuál fue la tasa de interés nominal mensual que obtuvo?
b) ¿Cuál fue la tasa de interés real que obtuvo, si la inflación fue de 5\%?


### :
&nbsp; Si hago un depósito de \$100.000 en una cuenta que entrega un interés de 10\% anual, ¿Cuánto dinero habrá en la cuenta después de 3 años?


### :

&nbsp; Si tengo \$250.000 y quiero que se transformen en \$320.000 en un fondo que entrega 2.5\% de rentabilidad anual, ¿Cuánto tiempo debo esperar?

