## Sobre capítulo II:

### Análisis de la curva de oferta en el mercado del trigo:

  Sean Qo y Qd las ecuaciones de oferta y demanda de un bien X, respectivamente. $$Q_o = 50P-300$$ $$Q_d=150-10P$$   Calcule el precio y cantidad de equilibrio.

  **RESPUESTA:**   Para obtener el equilibrio de mercado del bien X, es necesario entender que en el equilibrio $Q_o = Q_d=Q_{equilibrio}$ y $P_o = P_d=P_{equilibrio}$. Entonces: $$Q_o = 50P-300$$ $$Q_d=150-10P$$ $$\Rightarrow 150 -10P=50P-300$$ $$ \leftrightarrow 450=60P$$ $$ \leftrightarrow 7,5=P_{equilibrio}$$ $$\Rightarrow Q_o(P_{equilibrio})=Q_d(P_{equilibrio})=150 -10(7,5)=75$$

### Cambios en la demanda de smartphones ante una variación de precios:

a)  Calcule el precio oferido ($P$) de un bien para una producción de 7 unidades ($b=7$). Usted sabe que si no se producen unidades el precio oferido es de \$1000. Adicionalmente, usted sabe que la función de oferta es lineal de la forma: $$P(Q)=a+250Q$$

b)  Calcule cuál es la pendiente de una oferta lineal de un bien que vale \$1.500 cuando se han producido 2 unidades y vale \$1.000 cuando han producido 12 unidades.

c)  Asuma una función de oferta igual a $P(Q)=a+235Q$. Si Usted sabe que 17 unidades se valoran a un precio de 7820, ¿Cuál sería el precio de referencia si no se produce nada? %Diga cuánto vale un bien cuando su cantidad producida es 0, su pendiente es 235 y se han producido 17 unidades y actualmente vale 7820.

  **RESPUESTAS:**

a)  

  Para $Q=0$ tenemos que $P(0)=a+250\cdot 0=1000$. Luego sabemos que $a=1000$. De esa forma, calculando $P(7)=1000+250\cdot7=2750.$

b)  

$$\begin{matrix}
        1500 = a + b\cdot12  \\
        1000 = a + b\cdot2 
\end{matrix}$$

$$500 = 10b$$ $$b=50$$   La pendiente es igual a 50.

c)  

$$7820=a+17\cdot235$$ $$7820=a+3995$$ $$a=3825$$   El precio cuando no hay producción es igual a 3825

### Determinación del equilibrio de mercado en la industria del acero:

a)  Defina el concepto de cantidad demandada y Ley de Demanda.

b)  ¿Por qué la curva de demanda tiene pendiente negativa?

c)  ¿Qué es un incremento en la demanda? De un ejemplo.

d)  ¿Qué es un decremento de la demanda? De un ejemplo.

e)  Imagine que el promedio de los ingresos de la población chilena aumenta en un 1%. Esto produce una disminución en la demanda de la cerveza Cristal y un aumento en la demanda de cerveza Austral. ¿Qué tipo de bien es cada uno?

f)  En el mercado de bebidas existen dos compradores, Felipe y Catalina. Catalina tiene una curva de demanda $q = -p*(5/3) + 7$ y Felipe una curva de demanda de $p= -q*(1/4) + 3$. A un precio de \$2,5, ¿cuál es la cantidad demandada en el mercado?

  **RESPUESTAS:**

a)  

  La cantidad demandada es la cantidad de un bien que los compradores están dispuestos y tienen la capacidad de comprar. La ley de Demanda: si todo lo demás se mantiene constante, la cantidad de un bien disminuye cuando el precio de un bien aumenta.

b)  

  Considerando que la curva de demanda se dibuja con la cantidad demandada en el eje x y el precio en el eje y. Esta tiene pendiente negativa ya que refleja el beneficio marginal del consumidor. El beneficio marginal, o ganas de pagar, del consumidor disminuye a medida que consumimos unidades adicionales ya que obtenemos menos satisfacción por cada producto adicional. Viéndolo por otro lado, si el precio de un bien disminuye, más personas están dispuestas a comprarlo.

c)  

  Un incremento de la demanda es que la curva de demanda se desplace a la derecha, reflejando que, para todo precio de mercado, existirá una mayor cantidad demandada. Por ejemplo, un incremento en los precios de las bencinas incrementa la demanda de los autos eléctricos de cualquier precio.

d)  

  Un decremento de la demanda es lo contrario el incremento, este es el desplazamiento a la izquierda de la curva de demanda, reflejando que, para todos los precios de mercado, la cantidad demandada disminuye. Por ejemplo, un aumento en las tasas de interés disminuye la cantidad demandada de las acciones.

e)  

  Cristal es un bien inferior mientras que Austral es un bien normal.

f)  

  Primero debemos tener ambas curvas de la misma forma: $$Catalina: q = -p \cdot (5/3) + 7$$ $$Felipe: q = 12 - 4p$$

  La cantidad demandada en un mercado es la suma de las cantidades demandadas por todos los compradores en cada precio. $$Q = q1 + q2 + q3 …. +qn$$   Catalina: $$q= \frac{-2.5 \cdot 5}{3} + 7$$ $$q= 2.83$$   Felipe: $$q = 12 – 4 \cdot 2,5$$ $$Q =4.83$$
