project:
  type: book
  output-dir: docs
  

book:
  title: "Fundamentos de Economía"
  author: "Sebastián Cea, Joaquín Fernández, Reimundo Fuenzalida"
  repo-url: https://github.com/ingUANDES/fundeco
  # repo-actions: [edit]
  date: today
  language: es
  chapters:
    - index.qmd
    - intro.qmd
    - funcionamiento.qmd
    - intervencion.qmd
    - sistimpo.qmd
    - macro.qmd
    - finan.qmd
    # - 7,8titulo.qmd
    # - 14ejsinpauta.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    
  pdf:
    documentclass: scrreport
    include-in-header: 
      - text: |
          \usepackage{multirow}
          \usepackage{array} 
          \usepackage{hhline}
          \usepackage{pgfplots}
          \usepackage{multicol}

editor: visual

# execute:
#   cache: true
