project:
  type: book
  output-dir: docs

book:
  title: "Fundamentos de Economía"
  author: "Sebastián Cea, Joaquín Fernández, Reimundo Fuenzalida"
  date: "2023-2024"
  language: es
  chapters:
    - index.qmd
    - intro.qmd
    - funcionamiento.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    include-in-header: 
      - text: |
          \usepackage{multirow}
          \usepackage{array} 
          \usepackage{hhline}

editor: visual

