project:
  type: book
  output-dir: docs
  

book:
  title: "Fundamentos de Economía"
  author: "Sebastián Cea, Joaquín Fernández, Reimundo Fuenzalida"
  date: "2023-2024"
  language: es
  chapters:
    - index.qmd
    - intro.qmd
    - funcionamiento.qmd
    - 3interverción.qmd
    - 4sistimpo.qmd
    - 5varia.qmd
    - 6finan.qmd
    - 7,8titulo.qmd
    - 8ej_pauta1.qmd
    - 9ej_pauta2.qmd
    - 10ej_pauta3.qmd
    - 11ej_pauta4.qmd
    - 12ej_pauta5.qmd
    - 13ej_pauta6.qmd
    - 14ejsinpauta.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    
  pdf:
    documentclass: scrreport
    include-in-header: 
      - text: |
          \usepackage{multirow}
          \usepackage{array} 
          \usepackage{hhline}
          \usepackage{pgfplots}
          \usepackage{multicol}

editor: visual

