# Ayudantía I:

## Ejercicio I:

1)  A causa de las constantes enfermedades pulmonares y riesgos para la salud, el gobierno decide aumentar el impuesto al tabaco. Como consecuencia de esto, un 37% de los fumadores deja este vicio y hay un 45% menos de enfermedades relacionadas al uso de esta ¿Qué principio esta relacionado con este cambio económico?
2)  Dado que bajaron las enfermedades y que el estado logró recaudar más dinero por el aumento del impuesto anterior, el gobierno decide aumentar más aún el impuesto a este bien de consumo. Esta vez, aumento el mercado negro de este servicio y junto a esto, el estado recaudó menos y por la mala calidad del tabaco traficado aumento un %15 las enfermedades relacionadas a este habito. ¿Qué principio es el que esta relacionado con este nuevo cambió?
3)  Ahora, un comprador cualquiera de cigarrillos al ver que subieron los impuestos, tiene que decidir entre comprar una cajetilla o comprar la revista que compra todos los domingos ¿Que principio es el que se relaciona a esta situación?

## Ejercicio II:

  Con respecto al modelo de economía circular.
1) ¿Qué demandan los hogares?
2) ¿Qué demandan las empresas?
3) ¿Qué ofrecen los hogares?
4) ¿Qué ofrecen las empresas?


## Ejercicio III :

  Un lechero tiene como salario diario 15 dólares, trabaja desde las 6 de la mañana, hasta las 7 de la tarde, luego se junta con sus amigos, que tienen el mismo horario laboral, a cazar conejos hasta las 10 de la noche, finalmente se reúne con su familia, que solo están en la casa desde las 10 de la noche hasta las 6 de la mañana, para hacer conejo al escabeche hasta las 12 de la madrugada, si le ofrecen duplicar su sueldo, pero ahora tendrá que trabajar como guardia desde las 7 de la tarde hasta las 6 de la mañana.\

a)  ¿le es conveniente?

b)  ¿Bajo qué principio objetivo podría actuar este lechero?




  **RESPUESTAS**:

&nbsp; Ejercicio I:

1)  "En ocasiones, el gobierno puede mejorar los resultados del mercado." Ya que, al eliminar una externalidad negativa (un efecto negativo del mercado hacia la sociedad) está dando buenos resultados en el mercado. Dicho de otra forma, está mejorando la distribución de los bienes.
2)  "Normalmente, los mercados son un buen mecanismo de asignación de recursos." Al empeorar la situación sanitaria de la sociedad, a a través, de la intervención estatal, podemos concluir que en este caso, era mejor que el mercado no se intrevenga más.
3)  En este caso, los principios 1,2 hacen efecto en este evento, y dependiendo del caso, el 4 también hace efecto. Para el primer principio el comprador tiene que decidir entre una cosas o otra, para el segundo tendrá que renunciar a una de las dos y para el cuarto en el caso que escoja la revista, el impuesto dado es un incentivo que afecta el mercado.

&nbsp; Ejercicio II:

  Al demandar, decimos que este agente es el que quiere el bien o servicio. Por otro lado, al ofrecer, decimos que el agente es el dueño de este y que lo esta ofreciendo a cambio de algo.

1)  Los hogares demandan bienes y servicios.
2)  La empresa demanda factores de producción, es decir, trabajo, capital, tierra y tecnología.
3)  los hogares ofrecen factores de producción.
4)  las empresas ofrecen bienes y servicios.

&nbsp; Ejercicio III:


a)  

Depende de muchos factores. Luego es una pregunta subjetiva, cuyas respuestas intuitivas podrían ser:

-   Si, porque con el sueldo puede comprar comida para la familia.

-   Si, porque le hará bien un cambio de rutina.

-   No, porque el cambio de horario le puede enfermar y gastar más.

-   No, porque deja su vida social.

b)  

"El costo de algo es aquello a lo que se renuncia por obtenerlo."


