# Ayudantía VII:


## Ejercicio I:

  Reconozca la externalidad y su tipo, es decir, si es positiva o negativa, en los siguientes casos y proponga en que caso podría ser bueno aplicar un impuesto o un subsidio.

1)  Una empresa de textiles sintéticos que da una alta taza de empleo en la zona contamina las aguas de los ríos cercanos.

2)  Una empresa forestal imaginaria de monocultivo en la provincia del Malleco erosiona los suelos, esta produce un 15% del PIB nominal de Chile.

3)  Un criadero de caballos usados para deportes nacionales amansa a las crías en conjunto a una clínica que usa a estos para terapia.

4)  Una fundación para ancianos tiene una buena administración, pero no tiene los suficientes recursos para calefacción.


## Ejercicio II:

  Para un mercado de libros tenemos las siguientes funciones de oferta y demanda:

$$
\begin{array}{cc} P(Q)=5+2Q & Q(P)=15-P\\\end{array}
$$

  Calcule cuanto es la máxima recaudación posible teniendo en cuenta la curva de Laffer.

## Ejercicio III:

  Defina con sus palbras los siguintes terminos:
1) Déficit presupuestario:
2) Superávit presupuestal:
3) Equidad horizontal:
4) Equidad vertical:
5) Impuestos proporcionales:
6) Impuestos regresivos:
7) Impuestos progresivos:

## Ejercicio IV:

  Un mercado no regulado, está constituido por un solo productor y varios compradores, tiene de funciones de oferta y demanda $P(Q)=1+Q$ y $P(Q)=5-Q$ respectivamente. El productor se corrompió y decidió aprovecharse del mercado y obtener el máximo beneficio posible. ¿Cuánto será su excedente?


## Ejercicio V:

  Imagine el mercado de las lámparas representado por las siguientes curvas de oferta y demanda: $$Q_d = 400 - 2P$$ $$Q_o = -60 + 2P$$. Además, el precio internacional de las lámparas es \$170.

a)  Calcule el equilibrio de mercado sin comercio internacional.

b)  Calcule el equilibrio de mercado si se abren al comercio internacional.

c)  Calcule como queda el equilibrio de mercado si se crea un impuesto que hace que la cantidad total exportada sea 140 unidades.



  **RESPUESTA:**
  
  Ejercicio I:

1)  Externalidad Negativa, se le debería aplicar un impuesto.
2)  Externalidad Negativa, se le debería aplicar un impuesto.
3)  Externalidad positiva, al no tener problemas por enunciado, se le debería mantener igual.
4)  Externalidad positiva, se le debería aplicar un subsidio.


&nbsp; Ejercicio II:

  Primero calculamos la demanda inversa: $$
Q(P)=15-P \longleftrightarrow P(Q)=15-Q
$$

  Inserto gráfico con un impuesto arbitrario para entender los siguientes pasos:

```{r, engine='tikz',echo=FALSE,out.width="60%"}
#| fig-align: center
\begin{tikzpicture}
    
        % oferta = P(Q)=1+Q
        % demanda libre = P(Q)=5-Q
        % demanda con impuesto = 6-Q
        
        
        % Etiquetas en el eje P
        % Area excedente del consumidor
        \fill[orange!60] (0,5.66) -- (1.33,4.33) -- (0,4.33) -- cycle;
        
        % Area excedente del productor
        \fill[blue!50] (0,1.66) -- (1.33,4.33) -- (0,4.33) -- cycle;
        
        % Area de impuesto recuadado.
        \fill[black!60] (0,3.88) -- (1.11,3.88) -- (1.11,4.55) -- (0,4.55)-- cycle;
        \draw [line width=1pt](0,3.88) -- (1.11,3.88);
        \draw [line width=1pt](0,4.55) -- (1.11,4.55);
        
        % perdida de eficiencia.
        \fill[black] (1.11,3.88) -- (1.11,4.55) -- (1.33,4.33) -- cycle;
        
        % demanda inicial
        \draw [blue, line width=1pt](0,5) -- (5,0); %P(Q)=15-Q
        
        % demanda impuesto
        \draw [blue, line width=1pt](0,5.66) -- (5.66,0); %P(Q)=15-Q
    
        % oferta
        \draw [red, line width=1pt](0,1.66) -- (1.66,5); %P(Q)=5+Q
           
        % Eje x
        \draw[black, line width=2pt] (0,0) -- (5.98,0) node[right] {Q};
        \draw[black, line width=1pt] (5.86,-0.15) -- (6.01,0);
        \draw[black, line width=1pt] (5.86,0.15) -- (6.01,0);
    
        % eje y
        \draw[black, line width=2pt] (0,0) -- (0,5.98) node[right] {P};
        \draw[black, line width=1pt] (-0.15,5.86) -- (0,6.01);
        \draw[black, line width=1pt] (0.15,5.86) -- (0,6.01);
    
        
\end{tikzpicture}
```

  Como se podrá ver, mientras más impuesto, crecerá de forma mayor el peso muerto, entonces intentaremos ver cuanto tiene que ser el impuesto, para que sea la máxima recaudación posible, para esto el peso muerto tiene que ser igual a lo recaudado

$$
Q_i\cdot (P_f-P_i)=\frac{(P_f-P_i)\cdot (Q_f-Q_i)}{2}
$$

$$
2Q_i=Q_f-Q_i
$$ $$
3Q_i=Q_f
$$

  Si calculamos el punto de equilibrio inicial nos da $(3+\frac{1}{3},11+\frac{2}{3})$, entonces reemplazamos en la ecuación:

$$
Q_f=3\cdot\frac{10}{3}
$$ $$
Q_f=10
$$

  Buscamos la nueva demanda con el nuevo punto de equilibrio.

$$
P_d(Q)=a-Q \longleftrightarrow a-10=5+2\cdot10
$$ $$
a=25+10=35
$$ $$
P_di(Q)=35-Q
$$

  Con esto calculamos el $P_f$:

$$
P_di(10/3)=35-\frac{10}{3}\leftrightarrow P_f=31.66
$$

  finalmente la máxima recaudación es: $$
Q_i\cdot (P_f-P_i)
$$ $$
\frac{10}{3}\cdot (31+\frac{2}{3}-(11+\frac{2}{3}))
$$ $$
\frac{10}{3}\cdot 20=66.66
$$

  Lo recaudado es \$66.66 por unidad.

&nbsp; Ejercicio III:

1)  Déficit presupuestario: Es cuando el gobierno gasta más de lo que recibe.
2)  Superávit presupuestal: Es cuando el gobierno gasta menos de lo que recibe.
3)  Equidad horizontal: Los contribuyentes con misma capacidad de pago, pagan igual cantidad.
4)  Equidad vertical: Los contribuyentes con mayor capacidad de pago, pagan más.
5)  Impuestos proporcionales: Es cuando todos pagan los impuestos con la misma fracción de sus ingresos,
6)  Impuestos regresivos: Es cuando los contribuyentes de mayor ingreso pagan una menor fracción de sus ingresos en impuestos con respecto a los que tienen menos.
7)  Impuestos progresivos: Es cuando los contribuyentes de menor ingreso pagan una menor fracción de sus ingresos en impuestos con respecto a los que tienen más.


  Ejercicio IV:

  Para esto, usaremos las siguientes ecuaciones:

  Para calcular el máximo de la curva de Laffer:

$$
\frac{(P_f-P_i)\cdot (Q_i-Q_f)}{2}=Q_f\cdot (P_f-P_i)
$$

  Para calcular el excedente total: $$
EC = \int_{0}^{Q_f}{P_f-P_s(Q) \ dQ} + Q_f\cdot (P_f-P_i) 
$$

  Primero calculamos el punto de equilibrio inicial, este será $(2,3)$

  Luego el punto de equilibrio final:

$$
\frac{(P_f-P_i)\cdot (Q_i-Q_f)}{2}=Q_f\cdot (P_f-P_i)
$$ $$
\frac{(Q_i-Q_f)}{2}=Q_f
$$ $$
Q_f=\frac{2}{3}
$$

  Ahora el $P_f$ lo vemos con la demanda:

$$
P(2/3)=5-\frac{2}{3}=\frac{13}{3}
$$

  Finalmente el nuevo punto inicial es $(2/3,13/3)$

  Ahora reemplazamos en la ecuación del nuevo excedente: $$
EC = \int_{0}^{2/3}{\frac{5}{3}-1+Q \ dQ} + \frac{2}{3}\cdot (\frac{13}{3}-3)
$$ $$
EC = \frac{26}{9}+\frac{4}{9}+ \frac{2}{3}\cdot \frac{4}{3}
$$ $$
EC = \frac{26}{9}+\frac{4}{9}+ \frac{2}{3}\cdot \frac{4}{3}
$$ $$
EC = \frac{38}{9}
$$


  Ejercicio V:

a)  Para la primera parte necesitamos calcular el equilibrio de mercado, a partir de la intersección de las curvas de oferta y demanda dadas, donde obtenemos un precio de equilibrio $P=115$ y una cantidad de equilibrio $Q=170$.

b)  Ahora necesitamos calcular el equilibrio de ese mercado una vez que se abren al comercio internacional con un precio $P_I=170$. Reemplazando ese precio en la oferta y la demanda obtenemos $Q_o=280$ y $Q_d=60$. Como la oferta es mayor a la demanda en ese mercado, vemos que las exportaciones en este caso son: $$Exp = Q_o - Q_d = 280-60=220$$

c)  Si se crea un impuesto que hace que la cantidad exportada sea igual a 140, debemos hacer que las exportaciones, es decir, la cantidad ofertada menos la demandada, sea igual a 140 en lugar de 220 como en la pregunta anterior. Para eso hacemos lo siguiente: $$Exp = Q_o - Q_d = 140$$ $$(-60+2P)-(400-2P)=140$$ $$-460+4P=140$$ $$4P=600$$ $$P=150$$   Reemplazando ese nuevo precio de equilibrio en la oferta y en la demanda se obtiene respectivamente: $$Q_d = 400 - 2\cdot 150 = 100$$ $$Q_o = -60 + 2\cdot 150 = 240$$   Por lo que ahora la exportaciones son: $$Exp = Q_o - Q_d = 240 - 100 = 140$$   Además, el monto del impuesto es de 20, la diferencia del precio internacional $P_I=170$ y el nuevo precio de equilibrio $P=150$.

