# Introducción a la economía.

## Definición y clasificación de la economía:

La palabra economía significa literalmente "administración del hogar",\footnote{Del griego \emph{oikos} y \emph{nomos}.} pero su definición es "el estudio del modo en que la sociedad asigna recursos escasos a necesidades múltiples". Los recursos pueden ser o no escasos, para los que lo son se le llaman recursos económicos, y para los que no recursos libres. Los libres no tienen un valor económico, por lo tanto, tampoco tienen dueños. A ambos bienes las personas les otorgan un valor.\footnote{Se puede distinguir entre valor de uso y valor de intercambio de acuerdo a David Ricardo.} En particular, los recursos escasos generan un \emph{trade-off}, por lo que surge un problema para asignar su valor.

{\color{red}La economía estudia el modo en que la sociedad gestiona sus recursos escasos, es más, el problema fundamental de la economía es la \textbf{escasez de recursos.} Si no existiera este problema, la ciencia de la economía no existiría. Esta ciencia busca entender el modo en que se interrelacionan las personas a nivel económico, es decir, en el mercado. Para que exista este último termino, tiene que haber compradores y vendedores que realicen transacciones de entre ellos, ya sea de forma física o no.}

<!-- #El texto de arriba viene de clases de texto, 1.1 parte 1 linea 4. -->

\color{black}

Existen dos tipos de niveles de estudio de la economía, la microeconomía que estudia unidades económicas individuales y la macroeconomía que estudia variables económicas agregadas. Un sistema económico es la forma en que se asignan los recursos, existen los centralizados, es decir, los que un solo planificador asigna los recursos, los descentralizados, que la sociedad en general asigna los recursos y los mixtos, que asignan algunos bienes el estado y el otro la sociedad. La econometría es el estudio de estas cuestiones basado en técnicas estadísticas para testear postulados macroeconómicos y microeconómicos.

\underline{\textbf{En resumen:}}

::: {.content-visible when-format="html"}
```{=html}
<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-c3ow{border-color:inherit;text-align:center;vertical-align:top}
.tg .tg-0pky{border-color:inherit;text-align:left;vertical-align:top}
</style>
<table class="tg" style="undefined;table-layout: fixed; width: 710px">
<colgroup>
<col style="width: 86px">
<col style="width: 111px">
<col style="width: 235px">
<col style="width: 278px">
</colgroup>
<thead>
  <tr>
    <th class="tg-0pky">Tipo</th>
    <th class="tg-0pky">Clasificación</th>
    <th class="tg-0pky">Definición</th>
    <th class="tg-0pky">Ejemplo</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-c3ow" rowspan="3">Sistema Económico:</td>
    <td class="tg-0pky">Centralizado</td>
    <td class="tg-0pky"> Un solo agente administra todos los bienes.</td>
    <td class="tg-0pky"> El gobierno regulariza, produce y administra todos los bienes.</td>
  </tr>
  <tr>
    <td class="tg-0pky">Descentralizado</td>
    <td class="tg-0pky"> Los bienes son repartidos por la sociedad. Rol ejercido por el mercado.</td>
    <td class="tg-0pky"> Varias empresas producen un mismo bien, por lo que la sociedad escoge a quien comprar.</td>
  </tr>
  <tr>
    <td class="tg-0pky">Mixto</td>
    <td class="tg-0pky"> Algunos bienes o mercados son centralizados y otros descentralizados.</td>
    <td class="tg-0pky"> El petróleo tiene intervenidos los precios y el gobierno tiene el monopolio de distribución. En contraste, el maíz es producido por distintos semilleros.</td>
  </tr>
  <tr>
    <td class="tg-c3ow" rowspan="3">Niveles de Estudio:</td>
    <td class="tg-0pky">Microeconomía</td>
    <td class="tg-0pky"> Estudio de unidades económicas individuales.</td>
    <td class="tg-0pky"> La administración de una familia o empresa.</td>
  </tr>
  <tr>
    <td class="tg-0pky">Macroeconomía</td>
    <td class="tg-0pky"> Estudio de unidades económicas agregadas.</td>
    <td class="tg-0pky"> La administración de un país en base a variables como el PIB, la UF, el desempleo, etc.</td>
  </tr>
  <tr>
    <td class="tg-0pky">Económicos</td>
    <td class="tg-0pky"> Tienen valor económico y son escasos.</td>
    <td class="tg-0pky"> El trigo, Los bienes raíces o el agua.</td>
  </tr>
  <tr>
    <td class="tg-0pky"></td>
    <td class="tg-0pky">Libres</td>
    <td class="tg-0pky"> No tienen valor económico.</td>
    <td class="tg-0pky"> El sol.</td>
  </tr>
</tbody>
</table>
```

:::

::: {.content-visible when-format="pdf"}

```{=tex}
\begin{table}[htb]
    \centering
    \begin{tabular}{|p{20mm}|p{30mm}|p{45mm}|p{45mm}|}
        \hline
        Tipo & Clasificación & Definición & Ejemplo \\ \hline
        \multirow{3}{3cm}{Sistema Económico:} & Centralizado & \hspace{2mm} Un solo agente administra todos los bienes. & \hspace{2mm} El gobierno regulariza, produce y administra todos los bienes.\\ \cline{2-4}
        & Descentralizado & \hspace{2mm} Los bienes son repartidos por la sociedad. Rol ejercido por el mercado. & \hspace{2mm} Varias empresas producen un mismo bien, por lo que la sociedad escoge a quien comprar.\\ \cline{2-4}
        & Mixto & \hspace{2mm} Algunos bienes o mercados son centralizados y otros descentralizados. & \hspace{2mm} El petróleo tiene intervenidos los precios y el gobierno tiene el monopolio de distribución. En contraste, el maíz es producido por distintos semilleros.\\ \cline{1-4}
        \multirow{3}{3cm}{Niveles de Estudio:} & Microeconomía & \hspace{2mm} Estudio de unidades económicas individuales. & \hspace{2mm} La administración de una familia o empresa. \\ \cline{2-4}
        & Macroeconomía & \hspace{2mm} Estudio de unidades económicas agregadas. & \hspace{2mm} La administración de un país en base a variables como el PIB, la UF, el desempleo, etc. \\ \cline{1-4}
        \multirow{3}{3cm}{Recursos:} & Económicos & \hspace{2mm} Tienen valor económico y son escasos. & \hspace{2mm} El trigo, Los bienes raíces o el agua. \\ \cline{2-4}
        & Libres & \hspace{2mm} No tienen valor económico. & \hspace{2mm} El sol. \\ \cline{1-4}
    \end{tabular}
    \caption{Clasificación de la economía.}
    \label{tabla:final}
\end{table}
```

:::

## Los Diez Principios de la economía:

Los diez principios de la economía son afirmaciones que muestran hechos relevantes del análisis económico de acuerdo a \cite{mankiw_principios_2012}. Estos responden a tres preguntas.

```{=tex}
\begin{enumerate}
    \item ¿Cómo los individuos toman decisiones? (eficiencia, escasez, costos de oportunidad e incentivos.) 
    \item ¿Cómo interactúan los individuos? (derechos de propiedad, fallas del mercado y externalidades.)
    \item ¿Cómo funciona la economía en su conjunto? (productividad, inflación y ciclo económico) 
\end{enumerate}
```
En la siguiente tabla se explican estas proposiciones:

```{=tex}
\begin{table}[H]
    \centering
    \scalebox{0.95}{\begin{tabular}{|p{20mm}|p{30mm}|p{37mm}|p{53mm}|}
        \hline
        Numero: & Principio: & Explicación: & Ejemplo: \\ \hline
        1 & \hspace{2mm} “Los individuos enfrentan disyuntivas.” & \hspace{2mm} Esto se refiere a escoger una cosa u otra. & \hspace{2mm} Los dos tipos de disyuntivas son: \par \hspace{2mm} \underline{Eficiencia}, es decir como la sociedad aprovecha al máximo sus recursos. \par \hspace{2mm} \underline{Equidad}, como la sociedad distribuye equitativamente los recursos. \par \hspace{2mm} Ambos tipos de disyuntiva son dependientes uno al otro. \\ \hline
        2 & \hspace{2mm} “El costo de algo es aquello a lo que se renuncia por obtenerlo.” & \hspace{2mm} Esto se refiere a \underline{“el costo} \underline{oportunidad”}, o bien, a lo que se renuncia por obtener otro bien. También se le conoce como \textit{precio sombra}. & \hspace{2mm} Comprar para el desayuno un plátano renunciando a comer una manzana. \\ \hline
        3 & \hspace{2mm} “Pensamiento marginal.” & \hspace{2mm} Solo venderemos algo si la \textit{ganancia marginal} supera el \textit{costo marginal}. & \hspace{2mm}  El costo de producir manzanas, con todos los gastos que conlleva, es menor al beneficio y por lo tanto al ingreso que me proporciona este. \\ \hline
        4 & \hspace{2mm} “Los individuos responden a incentivos.” & \hspace{2mm} Cuando hay cambios en los costos, beneficios o se hace propaganda, o publicidad en un producto. & \hspace{2mm} Si el plátano vale más que la naranja, compraré naranja, pero si el plátano hace mejor para la salud, compraré plátano. \\ \hline
        5 & \hspace{2mm} “El comercio puede mejorar el bienestar de todos.” & \hspace{2mm} Cuando hay \underline{competencia} todos ganan, o al menos, no se pierde. Hay más especialización y se intenta abaratar los costos sin perder la especialización. & \hspace{2mm} Chile puede producir autos, pero no será eficiente, porque china lo hace mejor, pero si puede vender cerezas, ya que, chile es superior a china en ese rubro. \\ \hline
        \end{tabular}}
    \caption{Principios de la economía (1-5).}
    \label{tabla:final}
\end{table}
```
```{=tex}
\begin{table}[H]
    \centering
    \begin{tabular}{|p{16mm}|p{30mm}|p{59mm}|p{40mm}|}
        \hline
        Numero: & Principio: & Explicación: & Ejemplo: \\ \hline
        6 & \hspace{2mm} “Normalmente, los mercados son un buen mecanismo de asignación de recursos.” & \hspace{2mm} Primer teorema del bienestar social \underline{(PTB):} La mano invisible de Adam Smith dice que los mercados se regulan solos y lo hacen bien. {\color{red}{Este principio concluye que es el egoísmo individual, con relación a la economía, el que trae mayores beneficios a la sociedad y no la solidaridad de los individuos.}}    & \hspace{2mm} Las personas producirán y comprarán pan según el precio que tengan las panaderías y la calidad que tenga. \\ \hline
        7 & \hspace{2mm} “En ocasiones, el gobierno puede mejorar los resultados del mercado.” & \hspace{2mm} Segundo teorema del bienestar social \underline{(STB):} Por fallas del mercado, externalidades o poder de mercado. & \hspace{2mm} Impuesto a las empresas que contaminan, evitan una externalidad negativa ayudando al común de la gente. \\ \hline
        8 & \hspace{2mm} “El nivel de vida de un país depende de su capacidad para producir bienes y servicios.” & \hspace{2mm} Un punto que afecta es el \underline{PIB per cápita}, lo que produce el país dividido su población. Y la \underline{productividad}, que es la cantidad de bienes y servicios producidos por cada unidad de trabajo. & \hspace{2mm} Chile no solo tiene un PIB per cápita mayor que el de sus vecinos de la región, sino que también tiene farmacias, supermercados, etc. \\ \hline
        9 & \hspace{2mm} “Los precios suben cuando el Banco Central imprime mucho dinero” & \hspace{2mm} \underline{Inflación:} o también desvalorización del valor de la moneda por su gran cantidad de circulación. & \hspace{2mm} Al imprimir más billetes hay más plata circulando, esto hace que se gaste más plata, pero que al mismo tiempo esta plata tenga menos valor, ya que, la cantidad de bienes y servicios en la economía siguen siendo los mismos. \\ \hline
        10 & \hspace{2mm} “La sociedad enfrenta una disyuntiva a corto plazo entre inflación y desempleo.” & \hspace{2mm} \underline{Curva de \cite{phillips_relation_1958}:} hay un intercambio de inflación por desempleo. \underline{Ciclo económico:} Hay una variación de intensidad en la actividad económica, como el empleo y la producción. & \hspace{2mm} La gran depresión (1929). \\ \hline
    \end{tabular}
    \caption{Principios de la economía (6-10).}
    \label{tabla:final}
\end{table}
```
<<<<<<< HEAD



=======
>>>>>>> 812b5c96615eb50dac8811ff6920faf85cc3f288

## Modelos y supuestos:
El análisis de un modelo económico toma en cuenta supuestos, los modelos económicos analizan: 
