<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.550">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Fundamentos de Economía - 7&nbsp; Ejercicios Resueltos:</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./14ejsinpauta.html" rel="next">
<link href="./6finan.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./7,8titulo.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Ejercicios Resueltos:</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Fundamentos de Economía</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ingUANDES/fundeco" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefacio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducción a la economía.</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./funcionamiento.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Funcionamiento de los mercados.</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3interverción.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Intervenciones del mercado.</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4sistimpo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Sistema impositivo y economía laboral.</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5varia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Variables macroeconómicas.</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./6finan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Introducción a las finanzas.</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./7,8titulo.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Ejercicios Resueltos:</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14ejsinpauta.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Ejercicios sin resolución:</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sobre-capítulo-i" id="toc-sobre-capítulo-i" class="nav-link active" data-scroll-target="#sobre-capítulo-i"><span class="header-section-number">7.1</span> Sobre capítulo I:</a>
  <ul class="collapse">
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section"><span class="header-section-number">7.1.1</span> :</a></li>
  <li><a href="#section-1" id="toc-section-1" class="nav-link" data-scroll-target="#section-1"><span class="header-section-number">7.1.2</span> :</a></li>
  <li><a href="#section-2" id="toc-section-2" class="nav-link" data-scroll-target="#section-2"><span class="header-section-number">7.1.3</span> :</a></li>
  <li><a href="#section-3" id="toc-section-3" class="nav-link" data-scroll-target="#section-3"><span class="header-section-number">7.1.4</span> :</a></li>
  <li><a href="#section-4" id="toc-section-4" class="nav-link" data-scroll-target="#section-4"><span class="header-section-number">7.1.5</span> :</a></li>
  <li><a href="#section-5" id="toc-section-5" class="nav-link" data-scroll-target="#section-5"><span class="header-section-number">7.1.6</span> :</a></li>
  <li><a href="#section-6" id="toc-section-6" class="nav-link" data-scroll-target="#section-6"><span class="header-section-number">7.1.7</span> :</a></li>
  </ul></li>
  <li><a href="#sobre-capítulo-ii" id="toc-sobre-capítulo-ii" class="nav-link" data-scroll-target="#sobre-capítulo-ii"><span class="header-section-number">7.2</span> Sobre capítulo II:</a>
  <ul class="collapse">
  <li><a href="#section-7" id="toc-section-7" class="nav-link" data-scroll-target="#section-7"><span class="header-section-number">7.2.1</span> :</a></li>
  <li><a href="#section-8" id="toc-section-8" class="nav-link" data-scroll-target="#section-8"><span class="header-section-number">7.2.2</span> :</a></li>
  <li><a href="#section-9" id="toc-section-9" class="nav-link" data-scroll-target="#section-9"><span class="header-section-number">7.2.3</span> :</a></li>
  </ul></li>
  <li><a href="#sobre-el-capítulo-iii" id="toc-sobre-el-capítulo-iii" class="nav-link" data-scroll-target="#sobre-el-capítulo-iii"><span class="header-section-number">7.3</span> Sobre el capítulo III:</a>
  <ul class="collapse">
  <li><a href="#section-10" id="toc-section-10" class="nav-link" data-scroll-target="#section-10"><span class="header-section-number">7.3.1</span> :</a></li>
  <li><a href="#section-11" id="toc-section-11" class="nav-link" data-scroll-target="#section-11"><span class="header-section-number">7.3.2</span> :</a></li>
  <li><a href="#section-12" id="toc-section-12" class="nav-link" data-scroll-target="#section-12"><span class="header-section-number">7.3.3</span> :</a></li>
  </ul></li>
  <li><a href="#sobre-capítulo-iv" id="toc-sobre-capítulo-iv" class="nav-link" data-scroll-target="#sobre-capítulo-iv"><span class="header-section-number">7.4</span> Sobre capítulo IV:</a>
  <ul class="collapse">
  <li><a href="#section-13" id="toc-section-13" class="nav-link" data-scroll-target="#section-13"><span class="header-section-number">7.4.1</span> :</a></li>
  <li><a href="#section-14" id="toc-section-14" class="nav-link" data-scroll-target="#section-14"><span class="header-section-number">7.4.2</span> :</a></li>
  <li><a href="#section-15" id="toc-section-15" class="nav-link" data-scroll-target="#section-15"><span class="header-section-number">7.4.3</span> :</a></li>
  <li><a href="#section-16" id="toc-section-16" class="nav-link" data-scroll-target="#section-16"><span class="header-section-number">7.4.4</span> :</a></li>
  <li><a href="#section-17" id="toc-section-17" class="nav-link" data-scroll-target="#section-17"><span class="header-section-number">7.4.5</span> :</a></li>
  </ul></li>
  <li><a href="#sobre-capítulo-v" id="toc-sobre-capítulo-v" class="nav-link" data-scroll-target="#sobre-capítulo-v"><span class="header-section-number">7.5</span> Sobre capítulo V:</a>
  <ul class="collapse">
  <li><a href="#section-18" id="toc-section-18" class="nav-link" data-scroll-target="#section-18"><span class="header-section-number">7.5.1</span> :</a></li>
  <li><a href="#section-19" id="toc-section-19" class="nav-link" data-scroll-target="#section-19"><span class="header-section-number">7.5.2</span> :</a></li>
  <li><a href="#section-20" id="toc-section-20" class="nav-link" data-scroll-target="#section-20"><span class="header-section-number">7.5.3</span> :</a></li>
  <li><a href="#section-21" id="toc-section-21" class="nav-link" data-scroll-target="#section-21"><span class="header-section-number">7.5.4</span> :</a></li>
  <li><a href="#section-22" id="toc-section-22" class="nav-link" data-scroll-target="#section-22"><span class="header-section-number">7.5.5</span> :</a></li>
  <li><a href="#section-23" id="toc-section-23" class="nav-link" data-scroll-target="#section-23"><span class="header-section-number">7.5.6</span> :</a></li>
  <li><a href="#section-24" id="toc-section-24" class="nav-link" data-scroll-target="#section-24"><span class="header-section-number">7.5.7</span> :</a></li>
  <li><a href="#section-25" id="toc-section-25" class="nav-link" data-scroll-target="#section-25"><span class="header-section-number">7.5.8</span> :</a></li>
  <li><a href="#section-26" id="toc-section-26" class="nav-link" data-scroll-target="#section-26"><span class="header-section-number">7.5.9</span> :</a></li>
  <li><a href="#section-27" id="toc-section-27" class="nav-link" data-scroll-target="#section-27"><span class="header-section-number">7.5.10</span> :</a></li>
  <li><a href="#section-28" id="toc-section-28" class="nav-link" data-scroll-target="#section-28"><span class="header-section-number">7.5.11</span> :</a></li>
  <li><a href="#section-29" id="toc-section-29" class="nav-link" data-scroll-target="#section-29"><span class="header-section-number">7.5.12</span> :</a></li>
  <li><a href="#section-30" id="toc-section-30" class="nav-link" data-scroll-target="#section-30"><span class="header-section-number">7.5.13</span> :</a></li>
  <li><a href="#section-31" id="toc-section-31" class="nav-link" data-scroll-target="#section-31"><span class="header-section-number">7.5.14</span> :</a></li>
  <li><a href="#section-32" id="toc-section-32" class="nav-link" data-scroll-target="#section-32"><span class="header-section-number">7.5.15</span> :</a></li>
  </ul></li>
  <li><a href="#sobre-capítulo-vi" id="toc-sobre-capítulo-vi" class="nav-link" data-scroll-target="#sobre-capítulo-vi"><span class="header-section-number">7.6</span> Sobre capítulo VI:</a>
  <ul class="collapse">
  <li><a href="#section-33" id="toc-section-33" class="nav-link" data-scroll-target="#section-33"><span class="header-section-number">7.6.1</span> :</a></li>
  <li><a href="#section-34" id="toc-section-34" class="nav-link" data-scroll-target="#section-34"><span class="header-section-number">7.6.2</span> :</a></li>
  <li><a href="#section-35" id="toc-section-35" class="nav-link" data-scroll-target="#section-35"><span class="header-section-number">7.6.3</span> :</a></li>
  <li><a href="#section-36" id="toc-section-36" class="nav-link" data-scroll-target="#section-36"><span class="header-section-number">7.6.4</span> :</a></li>
  <li><a href="#section-37" id="toc-section-37" class="nav-link" data-scroll-target="#section-37"><span class="header-section-number">7.6.5</span> :</a></li>
  <li><a href="#section-38" id="toc-section-38" class="nav-link" data-scroll-target="#section-38"><span class="header-section-number">7.6.6</span> :</a></li>
  <li><a href="#section-39" id="toc-section-39" class="nav-link" data-scroll-target="#section-39"><span class="header-section-number">7.6.7</span> :</a></li>
  <li><a href="#section-40" id="toc-section-40" class="nav-link" data-scroll-target="#section-40"><span class="header-section-number">7.6.8</span> :</a></li>
  <li><a href="#section-41" id="toc-section-41" class="nav-link" data-scroll-target="#section-41"><span class="header-section-number">7.6.9</span> :</a></li>
  <li><a href="#section-42" id="toc-section-42" class="nav-link" data-scroll-target="#section-42"><span class="header-section-number">7.6.10</span> :</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/ingUANDES/fundeco/edit/main/7,8titulo.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Ejercicios Resueltos:</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>En las siguientes paginas tendrás ejercicios con sus resoluciones.</p>
<section id="sobre-capítulo-i" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="sobre-capítulo-i"><span class="header-section-number">7.1</span> Sobre capítulo I:</h2>
<section id="section" class="level3" data-number="7.1.1">
<h3 data-number="7.1.1" class="anchored" data-anchor-id="section"><span class="header-section-number">7.1.1</span> :</h3>
<p>&nbsp; Un productor “<span class="math inline">\(A\)</span>” de chocolate tiene como factor limitante el cacao, si quiere producir chocolate dulce necesita “<span class="math inline">\(c\)</span>” de este bien por cada kg y si quiere producir chocolate amargo necesita “<span class="math inline">\(d\)</span>” de este bien por cada kg. Para gastar todo su cacao necesita producir “<span class="math inline">\(e\)</span>” kg de chocolate dulce y “<span class="math inline">\(f\)</span>” de chocolate amargo.</p>
<ol type="1">
<li>Haga la ecuación que represente las FPP.</li>
</ol>
<p><strong>RESPUESTA</strong></p>
<p>&nbsp; Primero definimos <span class="math inline">\(y_1\)</span> es el chocolate dulce, y el amargo es <span class="math inline">\(y_2\)</span>, luego: <span class="math display">\[
\bar{x}=cy_1+dy_2
\]</span></p>
<p>&nbsp; Por la segunda parte del enunciado tenemos que: <span class="math display">\[
\bar{x}=ec+df
\]</span></p>
<p>&nbsp; Finalmente: <span class="math display">\[
ec+df=cy_1+dy_2
\]</span></p>
<ol start="2" type="1">
<li>Haga el gráfico de esta ecuación.</li>
</ol>
<p><strong>RESPUESTA</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="7,8titulo_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="section-1" class="level3" data-number="7.1.2">
<h3 data-number="7.1.2" class="anchored" data-anchor-id="section-1"><span class="header-section-number">7.1.2</span> :</h3>
<p>&nbsp; Una economía produce solo dos bienes, cobre y vino. Hay solo dos trabajadores y cada uno puede trabajar 10 horas diarias, en esas horas pueden producir 4 libras de cobre, o 6 litros de vino.</p>
<ol type="a">
<li><p>Dibuje la FPP individual y agregada.</p></li>
<li><p>Si se producen 50 litros de vino y 30 libras de cobre, ¿es eficiente? Si se producen 15 más de cada uno, ¿sería eficiente o alcanzable?</p></li>
<li><p>Ahora suponga que los trabajadores tienen capacidades diferentes, el primero puede producir 3 libras de cobre o 7 litros de vino, y el otro puede producir 5 libras de cobre o 4 litros de vino. Plantee las FPP individuales y luego la agregada.</p></li>
<li><p>Si de la ecuación <span class="math inline">\(x^2+y^2 = 100\)</span> se obtiene la FPP. Explique por qué este ejemplo sería una generalización del caso anterior.</p></li>
</ol>
<p>&nbsp; <strong>RESPUESTAS:</strong></p>
<ol type="a">
<li></li>
</ol>
<p>&nbsp; Con FPP individual se hace referencia a graficar la función de 1 trabajador. Ausumiendo linealidad, para poder graficar se necesita encontrar la pendiente.</p>
<p><span class="math display">\[m=\frac{4}{6}=\frac{2}{3}\]</span> <span class="math display">\[C: cobre ; V: Vino\]</span> <span class="math display">\[C=40-\frac{2}{3}\cdot V\]</span></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="7,8titulo_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></p>
</figure>
</div>
</div>
</div>
<p>&nbsp; Para la FPP agregada se incorporan todos los productores de la economía en el contexto. Asumiendo que ambos productores tienen la misma capacidad, se duplican las producciones:</p>
<p><span class="math display">\[C=80-\frac{2}{3}V\]</span></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="7,8titulo_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></p>
</figure>
</div>
</div>
</div>
<ol start="2" type="a">
<li></li>
</ol>
<p>&nbsp; Asumiendo producción agregada. Se calcula si el punto de 50 V y 30 C se encuentra en la FPP.</p>
<p><span class="math display">\[C=80-\frac{2}{3}\cdot50 = 46,67 \Rightarrow 46,67 &gt; 30\]</span> &nbsp; Debido a que el punto se encuentra debajo de la curva de FPP, este punto es alcanzable pero ineficiente.</p>
<p>&nbsp; Ahora, si se producen 65 litros de vino y 45 libras de cobre: <span class="math display">\[C=80-\frac{2}{3}\cdot65 = 36,67 \Rightarrow 36,67 &lt; 45\]</span> &nbsp; Debido a que este punto se encuentra sobre la curva de FPP, este es un punto inalcanzable.</p>
<ol start="3" type="a">
<li></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="7,8titulo_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="7,8titulo_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="7,8titulo_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></p>
</figure>
</div>
</div>
</div>
<ol start="4" type="a">
<li></li>
</ol>
<p>&nbsp; Al observar el último gráfico realizado en la pregunta anterior, se logra entender como se comporta una economía en la realidad. No todos los productores tienen las mismas capcacidades, produciendo curvatura en la FPP agregada. Entonces, si se agregan cada vez más productores, se obtendría una función similar a <span class="math inline">\(x^2+y^2 = 100\)</span>:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="7,8titulo_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="section-2" class="level3" data-number="7.1.3">
<h3 data-number="7.1.3" class="anchored" data-anchor-id="section-2"><span class="header-section-number">7.1.3</span> :</h3>
<p>&nbsp; Existe una economía que puede prestar servicios de limpieza y producir corbatas, la economía en total dispone de 1000 horas de trabajo. El servicio de limpieza les toma 1/2 hora y producir la corbata 5 horas.</p>
<ol type="a">
<li>¿Cuántos servicios de limpieza se pueden ofrecer si destinan todos los recursos y la fuerza laboral sólo a eso?</li>
<li>¿Cuántas corbatas se pueden producir si se destinan todos los recursos y la fuerza laboral sólo a eso?</li>
<li>Dibuje la FPP.</li>
<li>¿Qué significa la pendiente de la FPP?</li>
<li>Calcule el costo de oportunidad de pasar de 100 a 200 servicios de limpieza.</li>
</ol>
<p>&nbsp; <strong>RESPUESTA:</strong></p>
<ol type="a">
<li></li>
</ol>
<p><span class="math display">\[L: limpieza ; C: corbata\]</span> <span class="math display">\[1000 \cdot 2 = 2000 corbatas en 1000 horas de trabajo\]</span></p>
<ol start="2" type="a">
<li></li>
</ol>
<p><span class="math display">\[C \Rightarrow 5 \frac{horas}{corbata}\]</span> <span class="math display">\[\frac{1000 horas}{5\frac{horas}{corbata}}=200 corbatas\]</span></p>
<ol start="3" type="a">
<li></li>
</ol>
<p>&nbsp; Asumiendo producción lineal:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="7,8titulo_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<ol start="4" type="a">
<li><p>&nbsp; La pendiente de una FPP significa el costo de oportunidad.</p></li>
<li></li>
</ol>
<p>&nbsp; Primero, se escribe la función de la FPP: <span class="math display">\[C=200-\frac{1}{10}L\]</span> <span class="math display">\[C(L=100)=200-\frac{1}{10}100=190\]</span> <span class="math display">\[C(L=200)=200-\frac{1}{10}200=180\]</span> <span class="math display">\[Costo de Oportunidad=190-180=10\]</span></p>
</section>
<section id="section-3" class="level3" data-number="7.1.4">
<h3 data-number="7.1.4" class="anchored" data-anchor-id="section-3"><span class="header-section-number">7.1.4</span> :</h3>
<p>&nbsp; Suponga que hay dos países, el país A y el B. Al país A le toma 2 horas laborales producir 1 kg de alimentos, y 10 horas laborales producir un computador, mientras que al país B le toma 10 horas producir los mismos alimentos y 12 horas producir el mismo computador. a) ¿Qué le diría a alguien que le dice “los habitantes del país A no tienen por que comerciar con los del país B, hacen lo mismo mucho más rápido”? b) ¿Cuál es el costo de oportunidad de producir 1 kg de alimento para el país A y B? ¿Y de vestuario?.</p>
<p>&nbsp; <strong>RESPUESTA:</strong></p>
<ol type="a">
<li></li>
</ol>
<p>&nbsp; País A: <span class="math display">\[2 hrs \Rightarrow 1 kg alimento\]</span> <span class="math display">\[10 hrs \Rightarrow 1 computador\]</span></p>
<p>&nbsp; País B: <span class="math display">\[10 hrs \Rightarrow 1 kg alimento\]</span> <span class="math display">\[12 hrs \Rightarrow 1 computador\]</span></p>
<p>&nbsp; Ventaja absoluta: Habilidad que se tiene para producir un bien usando menos insumos que otro productor. &nbsp; El país A tiene ventaja absoluta en la producción de ambos productos.</p>
<p>&nbsp; Ventaja comparativa: Habilidad para producir un bien con un costo de oportunidad menor que otro productor &nbsp; El país A al ser tan buen productor por hora, producir un producto en vez de otro en esa hora, produce un gran costo de oportunidad en relación a la cantidad producida. Mientras que el país B no tiene un costo de oportunidad mucho menor.</p>
<p>&nbsp; Debido a esto es que al país A, a pesar de tener ventaja absoluta, no tiene una ventaja comparativa superior a B por lo que si les conviene realizar comercio entre ellos.</p>
<ol start="2" type="a">
<li></li>
</ol>
<p>&nbsp; Costo de oportunidad país A: &nbsp; 1 computador cuesta 5kg de alimento <span class="math display">\[1 kg de alimento cuesta \frac{1}{5} computadores\]</span></p>
<p>&nbsp; Costo de oportunidad país B: <span class="math display">\[1 computador cuesta 1,2 kg de alimento\]</span> <span class="math display">\[1 kg de alimento cuesta 0,833 computadores\]</span></p>
<p>&nbsp; A tiene ventaja comparativa en alimento mientras que B la tiene en computadores.</p>
</section>
<section id="section-4" class="level3" data-number="7.1.5">
<h3 data-number="7.1.5" class="anchored" data-anchor-id="section-4"><span class="header-section-number">7.1.5</span> :</h3>
<p>&nbsp; Carlos es un entrenador de fútbol que puede entrenar y producir sólo dos posiciones, defensas (D) y mediocampistas (M). Carlos puede producir 15 defensas por mes o 5 mediocampistas por mes.</p>
<ol type="a">
<li><p>Escribe la ecuación que describe la producción de Carlos. (Asuma relación lineal)</p></li>
<li><p>Suponga que Carlos no está produciendo mediocampistas este mes. ¿Cuál es el costo de oportunidad de aumentar su producción de mediocampistas de 0 a 2?</p></li>
<li><p>¿Cuál es el costo de oportunidad de producir cada defensa?</p></li>
<li><p>¿Cuál es el costo de oportunidad de producir cada mediocampista?</p></li>
</ol>
<p>&nbsp; <strong>RESPUESTAS:</strong></p>
<ol type="a">
<li></li>
</ol>
<p>&nbsp; Asumiendo linealidad en la producción:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="7,8titulo_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></p>
</figure>
</div>
</div>
</div>
<p>&nbsp; Entonces, la FPP de Carlos sigue la siguiente función: <span class="math display">\[D=-3M+15\]</span></p>
<ol start="2" type="a">
<li></li>
</ol>
<p><span class="math display">\[D(M=0)=-3(0)+15= 15 \]</span> <span class="math display">\[D(M=2)=-3(2)+15=9 \]</span> &nbsp; El costo de oportunidad son 6 defensas.</p>
<ol start="3" type="a">
<li></li>
</ol>
<p>&nbsp; Como se menciona la linealidad, el costo de oportunidad será constante a lo largo de toda la producción.</p>
<p>&nbsp; Entonces para encontrar el costo de oportunidad de producir los defensas es necesario entender la producción por el lado de los mediocampistas:</p>
<p><span class="math display">\[D=-3M+15 \leftrightarrow M=-\frac{1}{3}D+5\]</span> <span class="math display">\[M(D=0)=-\frac{1}{3}(0)+5=5\]</span> <span class="math display">\[M(D=1)=-\frac{1}{3}(1)+5=5-\frac{1}{3}\]</span> <span class="math display">\[C.O = 5-\frac{1}{3} - 5= -\frac{1}{3}\]</span> &nbsp; El costo de oportunidad de producir cada defensa es de <span class="math inline">\(\frac{1}{3}\)</span> mediocampistas.</p>
<ol start="4" type="a">
<li></li>
</ol>
<p><span class="math display">\[D(M=0)=-3(0)+15=15\]</span> <span class="math display">\[D(M=1)=-3(1)+15=12\]</span> <span class="math display">\[C.O=15-12=3\]</span> &nbsp; El costo de oportunidad de producir cada mediocampistas es de 3 defensas.</p>
</section>
<section id="section-5" class="level3" data-number="7.1.6">
<h3 data-number="7.1.6" class="anchored" data-anchor-id="section-5"><span class="header-section-number">7.1.6</span> :</h3>
<p>&nbsp; En el siguiente gráfico, podemos ver la cantidad de los bienes azúcar y tabaco que se pueden producir con el factor productivo limitado hectáreas.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="7,8titulo_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></p>
</figure>
</div>
</div>
</div>
<p>&nbsp; Si la cantidad de hectáreas que se necesitan para producir una unidad de tabaco es <span class="math inline">\(a_2\)</span> y de azúcar es <span class="math inline">\(a_1\)</span>, encuentre:</p>
<ol type="a">
<li><p>La cantidad de hectáreas asignadas a azúcar son <span class="math inline">\(h_1=36\)</span> y la máxima producción posible equivale a <span class="math inline">\(9\)</span> unidades. ¿Cuántas hectáreas se necesitan por unidad de azúcar?<br>
</p></li>
<li><p>Sabemos que <span class="math inline">\(a_2=12\)</span>, <span class="math inline">\(a_1=4\)</span> y que la cantidad máxima de azúcar que se puede producir es <span class="math inline">\(144\)</span>. ¿Cuál es la cantidad máxima que se puede producir de tabaco?<br>
</p></li>
<li><p>En relación con los resultados de ``b”, encuentre la cantidad de tabaco que se produjo, si se producen <span class="math inline">\(3\)</span> unidades de azúcar.<br>
</p></li>
</ol>
<p>&nbsp; <strong>RESPUESTAS:</strong></p>
<ol type="a">
<li>&nbsp; Paso I: Escribir ecuación.</li>
</ol>
<p>&nbsp; Genéricamente tenemos:</p>
<p><span class="math display">\[h_1(y_1)=a_1y_1\]</span></p>
<p>&nbsp; Donde <code>$y_1$'' es la cantidad de azúcar que se produce,</code><span class="math inline">\(a_1\)</span>’’ es la cantidad de hectáreas que se necesitan para producir una unidad de azúcar y ``h’’ es la cantidad de hectáreas disponibles.</p>
<p>&nbsp; Paso II: Reemplazar y resolver.</p>
<p>&nbsp; Lo que buscamos es cuantas hectáreas se necesitan para obtener una unidad de azúcar. Sabiendo que no se usaron para tabaco, entonces reescribimos los datos: <span class="math display">\[36=9a_1\]</span></p>
<p>&nbsp; Al resolver nos damos cuenta que el resultado es que se necesitan <span class="math inline">\(4\)</span> hectáreas para producir una unidad de tabaco.<br>
</p>
<ol start="2" type="a">
<li></li>
</ol>
<p>&nbsp; Paso I: Escribir ecuación.</p>
<p>&nbsp; Genéricamente tenemos:</p>
<p><span class="math display">\[\bar h=a_1y_1+a_2y_2\]</span></p>
<p>&nbsp; Paso II: Remplazar las distintas situaciones y solucionar.</p>
<p><span class="math display">\[\bar h=a_1y_1 \Leftrightarrow \bar h=4*144=576\]</span> <span class="math display">\[h_2=a_1y_1 \Leftrightarrow  576=12y_1  \Leftrightarrow y_2=48\]</span></p>
<p>&nbsp; Entonces, se pueden producir máximo 48 unidades de tabaco.<br>
</p>
<ol start="3" type="a">
<li></li>
</ol>
<p>&nbsp; Paso I: Escribir ecuación.</p>
<p>&nbsp; Genéricamente tenemos:</p>
<p><span class="math display">\[\bar h=a_1y_1+a_2y_2\]</span></p>
<p>&nbsp; Paso II: Reemplazar las distintas situaciones y solucionar.</p>
<p><span class="math display">\[\bar h=a_1y_1 + a_2y_2\Leftrightarrow \bar 576=4*3+12y_2 \Leftrightarrow 576=12+12y_2\]</span> <span class="math display">\[h_2= 576- 12 \Leftrightarrow  564=12y_1  \Leftrightarrow y_1=47\]</span></p>
<p>&nbsp; Entonces, si producimos <span class="math inline">\(3\)</span> unidades de azúcar, se producen 47 unidades de tabaco.</p>
</section>
<section id="section-6" class="level3" data-number="7.1.7">
<h3 data-number="7.1.7" class="anchored" data-anchor-id="section-6"><span class="header-section-number">7.1.7</span> :</h3>
<p>Un musico reconocido acaba de lanzar un álbum, y un fan suyo es dueño de una empresa de textiles, le ofreció usar una tonelada de textiles para vender camisas con la carátula de su disco o fundas de cama con el símbolo de su grupo. Si para hacer una funda se necesitan 5 kilogramos y para hacer una camisa se necesitan 2 kilogramos, haga un gráfico de su FPP y exprese matemáticamente el problema.</p>
<p>&nbsp; <strong>RESPUETSA:</strong></p>
<p>&nbsp; Paso I: Escribir ecuación.</p>
<p>&nbsp; Genéricamente tenemos:</p>
<p><span class="math display">\[\bar t=a_1y_1+a_2y_2\]</span></p>
<p>&nbsp; Donde <code>$y_1$'' es la cantidad de fundas que se produce,</code><span class="math inline">\(a_1\)</span>’’ es la cantidad de textiles que se necesitan para producir una unidad de funda y ``t’’ es la cantidad de textiles disponibles.<br>
</p>
<p>&nbsp; Paso II: Remplazar las distintas situaciones y solucionar.</p>
<p><span class="math display">\[\bar t=a_1y_1 \Leftrightarrow 1000=5y_1 \Leftrightarrow 20=y_1\]</span></p>
<p>&nbsp; Entonces, se pueden producir máximo 20 unidades de fundas.</p>
<p><span class="math display">\[\bar t=a_2y_2 \Leftrightarrow 1000=2y_2 \Leftrightarrow 20=y_2\]</span></p>
<p>&nbsp; Entonces, se pueden producir máximo 500 unidades de camisas.</p>
<p>&nbsp; Paso III: Hacer el gráfico.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="7,8titulo_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="sobre-capítulo-ii" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="sobre-capítulo-ii"><span class="header-section-number">7.2</span> Sobre capítulo II:</h2>
<section id="section-7" class="level3" data-number="7.2.1">
<h3 data-number="7.2.1" class="anchored" data-anchor-id="section-7"><span class="header-section-number">7.2.1</span> :</h3>
<p>&nbsp; Sean Qo y Qd las ecuaciones de oferta y demanda de un bien X, respectivamente. <span class="math display">\[Q_o = 50P-300\]</span> <span class="math display">\[Q_d=150-10P\]</span> &nbsp; Calcule el precio y cantidad de equilibrio.</p>
<p>&nbsp; <strong>RESPUESTA:</strong> &nbsp; Para obtener el equilibrio de mercado del bien X, es necesario entender que en el equilibrio <span class="math inline">\(Q_o = Q_d=Q_{equilibrio}\)</span> y <span class="math inline">\(P_o = P_d=P_{equilibrio}\)</span>. Entonces: <span class="math display">\[Q_o = 50P-300\]</span> <span class="math display">\[Q_d=150-10P\]</span> <span class="math display">\[\Rightarrow 150 -10P=50P-300\]</span> <span class="math display">\[ \leftrightarrow 450=60P\]</span> <span class="math display">\[ \leftrightarrow 7,5=P_{equilibrio}\]</span> <span class="math display">\[\Rightarrow Q_o(P_{equilibrio})=Q_d(P_{equilibrio})=150 -10(7,5)=75\]</span></p>
</section>
<section id="section-8" class="level3" data-number="7.2.2">
<h3 data-number="7.2.2" class="anchored" data-anchor-id="section-8"><span class="header-section-number">7.2.2</span> :</h3>
<ol type="a">
<li><p>Calcule el precio oferido (<span class="math inline">\(P\)</span>) de un bien para una producción de 7 unidades (<span class="math inline">\(b=7\)</span>). Usted sabe que si no se producen unidades el precio oferido es de $1000. Adicionalmente, usted sabe que la función de oferta es lineal de la forma: <span class="math display">\[P(Q)=a+250Q\]</span></p></li>
<li><p>Calcule cuál es la pendiente de una oferta lineal de un bien que vale $1.500 cuando se han producido 2 unidades y vale $1.000 cuando han producido 12 unidades.</p></li>
<li><p>Asuma una función de oferta igual a <span class="math inline">\(P(Q)=a+235Q\)</span>. Si Usted sabe que 17 unidades se valoran a un precio de 7820, ¿Cuál sería el precio de referencia si no se produce nada? %Diga cuánto vale un bien cuando su cantidad producida es 0, su pendiente es 235 y se han producido 17 unidades y actualmente vale 7820.</p></li>
</ol>
<p>&nbsp; <strong>RESPUESTAS:</strong></p>
<ol type="a">
<li></li>
</ol>
<p>&nbsp; Para <span class="math inline">\(Q=0\)</span> tenemos que <span class="math inline">\(P(0)=a+250\cdot 0=1000\)</span>. Luego sabemos que <span class="math inline">\(a=1000\)</span>. De esa forma, calculando <span class="math inline">\(P(7)=1000+250\cdot7=2750.\)</span></p>
<ol start="2" type="a">
<li></li>
</ol>
<p><span class="math display">\[\begin{matrix}
        1500 = a + b\cdot12  \\
        1000 = a + b\cdot2
\end{matrix}\]</span></p>
<p><span class="math display">\[500 = 10b\]</span> <span class="math display">\[b=50\]</span> &nbsp; La pendiente es igual a 50.</p>
<ol start="3" type="a">
<li></li>
</ol>
<p><span class="math display">\[7820=a+17\cdot235\]</span> <span class="math display">\[7820=a+3995\]</span> <span class="math display">\[a=3825\]</span> &nbsp; El precio cuando no hay producción es igual a 3825</p>
</section>
<section id="section-9" class="level3" data-number="7.2.3">
<h3 data-number="7.2.3" class="anchored" data-anchor-id="section-9"><span class="header-section-number">7.2.3</span> :</h3>
<ol type="a">
<li><p>Defina el concepto de cantidad demandada y Ley de Demanda.</p></li>
<li><p>¿Por qué la curva de demanda tiene pendiente negativa?</p></li>
<li><p>¿Qué es un incremento en la demanda? De un ejemplo.</p></li>
<li><p>¿Qué es un decremento de la demanda? De un ejemplo.</p></li>
<li><p>Imagine que el promedio de los ingresos de la población chilena aumenta en un 1%. Esto produce una disminución en la demanda de la cerveza Cristal y un aumento en la demanda de cerveza Austral. ¿Qué tipo de bien es cada uno?</p></li>
<li><p>En el mercado de bebidas existen dos compradores, Felipe y Catalina. Catalina tiene una curva de demanda <span class="math inline">\(q = -p*(5/3) + 7\)</span> y Felipe una curva de demanda de <span class="math inline">\(p= -q*(1/4) + 3\)</span>. A un precio de $2,5, ¿cuál es la cantidad demandada en el mercado?</p></li>
</ol>
<p>&nbsp; <strong>RESPUESTAS:</strong></p>
<ol type="a">
<li></li>
</ol>
<p>&nbsp; La cantidad demandada es la cantidad de un bien que los compradores están dispuestos y tienen la capacidad de comprar. La ley de Demanda: si todo lo demás se mantiene constante, la cantidad de un bien disminuye cuando el precio de un bien aumenta.</p>
<ol start="2" type="a">
<li></li>
</ol>
<p>&nbsp; Considerando que la curva de demanda se dibuja con la cantidad demandada en el eje x y el precio en el eje y. Esta tiene pendiente negativa ya que refleja el beneficio marginal del consumidor. El beneficio marginal, o ganas de pagar, del consumidor disminuye a medida que consumimos unidades adicionales ya que obtenemos menos satisfacción por cada producto adicional. Viéndolo por otro lado, si el precio de un bien disminuye, más personas están dispuestas a comprarlo.</p>
<ol start="3" type="a">
<li></li>
</ol>
<p>&nbsp; Un incremento de la demanda es que la curva de demanda se desplace a la derecha, reflejando que, para todo precio de mercado, existirá una mayor cantidad demandada. Por ejemplo, un incremento en los precios de las bencinas incrementa la demanda de los autos eléctricos de cualquier precio.</p>
<ol start="4" type="a">
<li></li>
</ol>
<p>&nbsp; Un decremento de la demanda es lo contrario el incremento, este es el desplazamiento a la izquierda de la curva de demanda, reflejando que, para todos los precios de mercado, la cantidad demandada disminuye. Por ejemplo, un aumento en las tasas de interés disminuye la cantidad demandada de las acciones.</p>
<ol start="5" type="a">
<li></li>
</ol>
<p>&nbsp; Cristal es un bien inferior mientras que Austral es un bien normal.</p>
<ol start="6" type="a">
<li></li>
</ol>
<p>&nbsp; Primero debemos tener ambas curvas de la misma forma: <span class="math display">\[Catalina: q = -p \cdot (5/3) + 7\]</span> <span class="math display">\[Felipe: q = 12 - 4p\]</span></p>
<p>&nbsp; La cantidad demandada en un mercado es la suma de las cantidades demandadas por todos los compradores en cada precio. <span class="math display">\[Q = q1 + q2 + q3 …. +qn\]</span> &nbsp; Catalina: <span class="math display">\[q= \frac{-2.5 \cdot 5}{3} + 7\]</span> <span class="math display">\[q= 2.83\]</span> &nbsp; Felipe: <span class="math display">\[q = 12 – 4 \cdot 2,5\]</span> <span class="math display">\[Q =4.83\]</span></p>
</section>
</section>
<section id="sobre-el-capítulo-iii" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="sobre-el-capítulo-iii"><span class="header-section-number">7.3</span> Sobre el capítulo III:</h2>
<section id="section-10" class="level3" data-number="7.3.1">
<h3 data-number="7.3.1" class="anchored" data-anchor-id="section-10"><span class="header-section-number">7.3.1</span> :</h3>
<p>&nbsp; Argentina por razones populistas, antes de las elecciones decidido fijar los precios de algunos bienes. A base de esto en un pueblo imaginario tiene el mercado del queso como funciones de oferta y demanda respectivamente <span class="math inline">\(P(Q)=1.5+0.5Q\)</span> y <span class="math inline">\(Q(P)=5-P\)</span>. La fijación al precio máximo de este bien es de $2. ¿Qué fenómeno ocurrirá debido a esta intervención? Haga un gráfico de la situación.</p>
<p>&nbsp; <strong>RESPUESTA</strong></p>
<p>&nbsp; La función de demanda inversa es <span class="math inline">\(P(Q)=5-Q\)</span>. Además, ocurrirá un escasez y el gráfico es el siguiente:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="7,8titulo_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></p>
</figure>
</div>
</div>
</div>
<p>&nbsp; Donde el área negra es la escasez.</p>
</section>
<section id="section-11" class="level3" data-number="7.3.2">
<h3 data-number="7.3.2" class="anchored" data-anchor-id="section-11"><span class="header-section-number">7.3.2</span> :</h3>
<p>El mercado local de diesel está representado por:</p>
<p><span class="math display">\[Q = \frac{a-P}{12.5}  \hspace{1cm} \text{ y}   \hspace{1cm}   Q = \frac{P-b}{11}\]</span></p>
<p>&nbsp; Donde <span class="math inline">\(P\)</span> se encuentra en pesos chilenos ($) por litro de combustible y <span class="math inline">\(Q\)</span> muestra los litros de combustible (en millones) que se transan en este mercado. Actualmente se cobra un impuesto de $130 por litro de diesel.</p>
<ol type="a">
<li><p>Se le pide calcular la cantidad Q que se transa después de aplicado el impuesto. Exprese su resultado con dos decimales.</p></li>
<li><p>Muestre detalladamente los cálculos del ejercicio anterior. ¿Hay diferencia entre el precio que observan oferentes y demandantes? Si es así, cuál es el precio que observa el productor y cuál es el precio que observa el consumidor? ¿A cuánto asciende la recaudación del gobierno? Si hay pérdida de eficiencia, ¿a cuánto asciende? Grafique.</p></li>
<li><p>En su cálculo, ¿aplicó el impuesto sobre el consumidor o sobre el productor? ¿Sería diferente el resultado si lo aplica al otro lado del mercado? ¿Por qué? Calcule la incidencia del impuesto y relaciónelo con la elasticidad precio propio de las curvas de oferta y demanda.</p></li>
<li><p>En la actualidad, hay argumentos a favor de aumentar el impuesto sobre el diésel y otros argumentos a favor de disminuir (al menos temporalmente) ese mismo impuesto. Mencione al menos un argumento que apoye el alza de este impuesto y uno que apoye la disminución del impuesto. Y finalmente, concluya a favor de qué argumento se encuentra usted.</p></li>
</ol>
<p>&nbsp; <strong>RESPUESTAS:</strong></p>
<ol type="a">
<li><p>&nbsp; Con un impuesto unitario <span class="math inline">\(\tau=\)</span>$130, el precio que observan compradores y vendedores será diferente, tal que <span class="math inline">\(\tau=130=P_c - P_v\)</span> donde <span class="math inline">\(P_c\)</span> es el precio que observan y pagan los consumidores y <span class="math inline">\(P_v\)</span> es el precio que observan y reciben los oferentes por cada litro de combustible. Si se aplica el impuesto sobre los compradores, se tiene <span class="math inline">\(P_c= P_v+\tau\)</span> y reemplazando en la ecuación de la demanda para obtener el nuevo equilibrio: <span class="math display">\[ \frac{a-P_v-\tau}{12.5}=\frac{P_v-b}{11}\]</span> de donde <span class="math display">\[P_v = \frac{11a+12.5b-11\tau}{11+12.5}\]</span> <span class="math display">\[Q^\prime=\frac{a-b-\tau}{23.5}\]</span></p></li>
<li></li>
</ol>
<p>&nbsp; Sí, hay diferencia entre el precio que observan oferentes y demandantes. Por ejemplo, con <span class="math inline">\(a=900\)</span>, <span class="math inline">\(b=300\)</span> y <span class="math inline">\(\tau=130\)</span> antes del impuesto el equilibrio estaba dado por <span class="math inline">\(Q_0=25.53\)</span> millones de litros a un precio de <span class="math inline">\(P_0=580.85\)</span> por litro de diésel. Con el impuesto, el precio que reciben los oferentes por litro es de $520 (<span class="math inline">\(P_v\)</span>), mientras que los consumidores pagan por litro $650 (<span class="math inline">\(P_c\)</span>) y en el mercado se transa una menor cantidad que asciende a <span class="math inline">\(Q^\prime = 20\)</span> millones. En este caso, la recaudación del gobierno es de $2.600 millones (<span class="math inline">\(\tau Q^\prime\)</span>) y la pérdida de eficiencia es de $719,1 millones (<span class="math inline">\(\tau (Q_0-Q^\prime)\)</span>).</p>
<ol start="3" type="a">
<li></li>
</ol>
<p>&nbsp; El resultado es el mismo independientemente sobre quién se aplique el impuesto, puesto que finalmente la carga fiscal es compartida entre ambas partes del mercado (oferentes y demandantes). Sobre quién recae la mayor parte, depende de la sensibilidad ante los cambios en los precios del diésel (incidencia del impuesto), lo cual se calcula con la elasticidad precio propio de las curvas de oferta y demanda: <span class="math display">\[|\varepsilon_D | =\frac{\partial Q}{\partial P} \frac{P}{Q}=|\frac{-1}{12.5} \frac{P}{Q}| &lt; \frac{1}{11} \frac{P}{Q}=\frac{\partial Q}{\partial P} \frac{P}{Q}=\varepsilon_S\]</span> &nbsp; En este caso, para cualquier par <span class="math inline">\((Q, P)\)</span>, la demanda es siempre más inelástica que la oferta. Es decir, es menos sensible a cambios en precios, lo cual hace que la incidencia fiscal recaiga en mayor medida sobre los consumidores. En este caso, del impuesto unitario de $130, los consumidores pagan $69,15 del impuesto por cada litro y los productores $60,85 por litro.</p>
<ol start="4" type="a">
<li></li>
</ol>
<p>&nbsp; Argumentos para incrementar el impuesto: - disminuir el efecto de la externalidad negativa de la contaminación que genera su uso, (ii) progresividad del impuesto considerando que las familias de mayores ingresos son las tienen automóvil y hacen uso de este combustible y (iii) aumentar los ingresos del fisco considerando la necesidad de mayor gasto público por la pandemia. Argumentos para reducir el impuesto de forma temporal: - ayudar a las familias que han sufrido reducciones en el ingreso por la actual coyuntura de mayor desempleo, empresas con menores ingresos por medidas de confinamiento, etc. - incentivar la industria de transporte y el traslado en menores costos a otras empresas.</p>
</section>
<section id="section-12" class="level3" data-number="7.3.3">
<h3 data-number="7.3.3" class="anchored" data-anchor-id="section-12"><span class="header-section-number">7.3.3</span> :</h3>
<p>Tenemos un mercado donde su función oferta y demanda iniciales son respectivamente: <span class="math display">\[P(Q)=5+\frac{3}{2}Q, \quad \quad P(Q)=13-\frac{1}{2}Q\]</span> Luego sus funciones de oferta y demanda cambian respectivamente: <span class="math display">\[P(Q)=2+Q, \quad \quad P(Q)=15-aQ\]</span> a) Calcule el punto de equilibrio inicial.<br>
b) ¿Cuánto tendría que valer “a”, para que este mercado se absolutamente inelástico?<br>
c) Para el mismo caso, ¿Cuánto debería valer “a” para que su elasticidad sea unitaria?</p>
<p>&nbsp; <strong>RESPUESTAS:</strong></p>
<ol type="a">
<li><p>&nbsp; Igualamos las funciones y calculamos “Q”: <span class="math display">\[5+\frac{3}{2}Q=13-\frac{1}{2}Q\]</span> <span class="math display">\[2Q=8\]</span> <span class="math display">\[Q=4\]</span><br>
&nbsp; A base de la cantidad, calculamos el precio. <span class="math display">\[P(4)=13-\frac{1}{2}\cdot4\]</span> <span class="math display">\[P=11\]</span><br>
&nbsp; Entonces el punto de equilibrio está en <span class="math inline">\((4,11)\)</span>.<br>
</p></li>
<li><p>&nbsp; Al ser absolutamente inelástica, “Q” debe tener el mismo valor en la situación final e inicial. Entonces: <span class="math display">\[2+Q=15-aQ\]</span> <span class="math display">\[2+1\cdot 4 =15-a\cdot 4\]</span> <span class="math display">\[2+4-15=-4\cdot a\]</span> <span class="math display">\[9=4\cdot a\]</span> <span class="math display">\[a=2.25\]</span><br>
&nbsp; Entonces para que a sea absolutamente inelástica, “a” tiene que valer 2,25.</p></li>
<li><p>&nbsp; Para que su elasticidad sea unitaria, esta tiene que ser igual a 1, entonces formularemos la situación así: <span class="math display">\[1 =\left|\frac{\triangle\%Q}{\triangle\%P}\right|\]</span><br>
&nbsp; Simplificamos los “%”. <span class="math display">\[1 =\left|\frac{\triangle Q}{\triangle P}\right|\]</span><br>
&nbsp; Buscamos el valor de “Q”: <span class="math display">\[2+Q=15-aQ\]</span> <span class="math display">\[Q+aQ=13\]</span> <span class="math display">\[Q=\frac{13}{1+a}\]</span><br>
&nbsp; Y en relación con este, buscamos el valor de “P”: <span class="math display">\[P=15-\frac{13a}{1+a}\]</span><br>
&nbsp; Y finalmente formulamos: <span class="math display">\[1 =\left|\frac{Q_i-Q_f}{P_i-P_f}\right|\]</span> <span class="math display">\[1 =\left|\frac{4-\frac{13}{1+a}}{11-15+\frac{13a}{1+a}}\right|\]</span> <span class="math display">\[1 =\left|\frac{4-\frac{13}{1+a}}{-4+\frac{13a}{1+a}}\right|\]</span> <span class="math display">\[1 =\left|\frac{\frac{4(1+a)-13}{1+a}}{\frac{13a-4(1+a)}{1+a}}\right|\]</span> <span class="math display">\[1 =\left|\frac{4+4a-13}{13a-4-4a}\right|\]</span> <span class="math display">\[1 =\left|\frac{4a-9}{9a-4}\right|\]</span><br>
&nbsp; Como “a” está en la demanda expresada con un signo negativo, entonces <span class="math inline">\(a&gt;0\)</span>.<br>
&nbsp; Caso I: <span class="math display">\[1 =\frac{4a-9}{9a-4}\]</span> <span class="math display">\[9a-4 =4a-9\]</span> <span class="math display">\[5a=-5\]</span><br>
&nbsp; No se cumple por ser de valor negativo<br>
&nbsp; Caso II: <span class="math display">\[1 =-\frac{4a-9}{9a-4}\]</span> <span class="math display">\[9a-4 =-4a+9\]</span> <span class="math display">\[13a =13\]</span> <span class="math display">\[a =1\]</span><br>
&nbsp; Se cumple.<br>
&nbsp; Entonces a es igual a 1.</p></li>
</ol>
</section>
</section>
<section id="sobre-capítulo-iv" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="sobre-capítulo-iv"><span class="header-section-number">7.4</span> Sobre capítulo IV:</h2>
<section id="section-13" class="level3" data-number="7.4.1">
<h3 data-number="7.4.1" class="anchored" data-anchor-id="section-13"><span class="header-section-number">7.4.1</span> :</h3>
<p>&nbsp; Sea el mercado nacional de novelas formado por: los lectores locales <span class="math inline">\(Q_D = 700 - 5P\)</span> y los escritores locales <span class="math inline">\(Q_S = 25P - 2000\)</span>, donde <span class="math inline">\(P\)</span> es el precio por libro y <span class="math inline">\(Q\)</span> es la cantidad de libros. Además, el mercado está abierto al comercio internacional y las novelas de autores extranjeros tienen un precio de $70. &nbsp; Con esta información responda a las siguientes preguntas:</p>
<ol type="a">
<li><p>Calcule la cantidad de novelas escritas por autores nacionales y la cantidad de novelas escritas por autores extranjeros que los lectores locales comprarían. Calcule además el excedente total del mercado nacional.</p></li>
<li><p>Los escritores nacionales se organizan y deciden pedir apoyo del estado. ¿Qué argumentos cree que utilizarían?</p></li>
<li><p>Imagine que el estado acepta la petición de los escritores nacionales y decide fijar un arancel de $10 por libro importado. Calcule la recaudación que logra el estado y la pérdida de eficiencia que genera el arancel. ¿Por qué este arancel no ayuda en nada a los escritores locales?</p></li>
<li><p>Luego del fracaso del arancel, los escritores organizados nuevamente acuden al estado pero ahora con una propuesta concreta: eliminar por completo la importación de libros. ¿De qué tamaño debe ser el arancel para lograr esto? ¿Cuál sería la recaudación y cuál la pérdida de eficiencia si el estado aplica la propuesta?</p></li>
</ol>
<p>&nbsp; <strong>RESPUESTAS:</strong></p>
<ol type="a">
<li></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="7,8titulo_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></p>
</figure>
</div>
</div>
</div>
<p>&nbsp; Luego se tiene que <span class="math inline">\(Q_D = 700 - 5(70) = 350\)</span>. Novelas locales = 0 y novelas extranjeras = 350 <span class="math display">\[ET = 350(70)\div2 = 12,250\]</span></p>
<ol start="2" type="a">
<li></li>
</ol>
<p>&nbsp; Respuesta abierta. Podrían decir que no logran vender nada y hay que apoyar a la industria local: empleos, literatura local, etc.</p>
<ol start="3" type="a">
<li></li>
</ol>
<p>&nbsp; Ahora <span class="math inline">\(P = 80 ==&gt; Q_D = 700 - 5(80) = 300\)</span>, <span class="math inline">\(Q_S = 0\)</span>. la recaudación es <span class="math inline">\(R = 300(10) = 3,000\)</span> El nuevo excedente total es ahora <span class="math inline">\(ET = 300(60)\div2 = 9,000\)</span>. La pérdida de eficiencia es <span class="math inline">\(PE = 12, 250 - 9, 000 = 3, 250\)</span>. No les ayuda en nada porque a $80 el libro extranjero, ellos aún no logran vender.</p>
<ol start="4" type="a">
<li>&nbsp; El arancel debe ser tal que nadie quiera importar, es decir <span class="math inline">\(Q_D = Q_S: 700 - 5P = 25P - 2000\)</span>, de donde P = $90 y arancel= $20. Si nadie importa, la recaudación es nula. El excedente total es ahora <span class="math inline">\(ET = 250(60)\div2 = 7,500\)</span> y la pérdida de eficiencia es <span class="math inline">\(PE = 12,250 - 7,500 = 4,750\)</span>.</li>
</ol>
</section>
<section id="section-14" class="level3" data-number="7.4.2">
<h3 data-number="7.4.2" class="anchored" data-anchor-id="section-14"><span class="header-section-number">7.4.2</span> :</h3>
<p>&nbsp; Una empresa tiene costos totales dados por <span class="math inline">\(CT = {Q}^2 + 5Q + 36\)</span>, sabiendo esto calcule lo siguiente:</p>
<ol type="a">
<li><p>Función de costos marginales para la empresa.</p></li>
<li><p>Costo variable medio.</p></li>
<li><p>Costo toal medio.</p></li>
</ol>
<p>&nbsp; Ahora repita los mismos calculos para un empresa con <span class="math inline">\(CF = 200\)</span> y <span class="math inline">\(CV = 2{Q}^2 + 8Q\)</span> en d,e,f.</p>
<p>&nbsp; <strong>RESPUESTAS:</strong></p>
<ol type="a">
<li><p>Derivando la función de los costos totales obtenemos <span class="math inline">\(CMG = 2Q + 5\)</span></p></li>
<li><p>Para obtener el costo variable medio debemos separar los costos totales y fijos. Los costos fijos serían <span class="math inline">\(CF = 36\)</span> y los costos variables <span class="math inline">\(CV = {Q}^2 + 5Q\)</span>. Para el costo variable medio hay que dividir por Q. Quedando así <span class="math inline">\(CVMe = \frac{{Q}^2+ 5Q}{Q} = Q + 5\)</span>.</p></li>
<li><p>Los costos totales medios son los costos totales divididos por Q. De esta forma quedaría: <span class="math display">\[CTMe = \frac{{Q}^2 + 5Q + 36}{Q} = Q + 5 + \frac{36}{Q}\]</span></p></li>
<li><p>Para esta nueva empresa, armamos la función de costo total sumando los costos fijos más los variables. Obtenemos <span class="math inline">\(CT = 2{Q}^2 + 8Q + 200\)</span>. Derivamos respecto a Q y obtenemos los costos marginales <span class="math inline">\(CMg = 4Q + 8\)</span>.</p></li>
<li><p>Para los costos variables medios obtenemos <span class="math inline">\(CVMe = \frac{2{Q}^2 + 8Q}{Q} = 2Q + 8\)</span>.</p></li>
<li><p>Para los costos totales medios obtenemos <span class="math inline">\(CTMe = \frac{2{Q}^2 + 8Q + 200}{Q} = 2Q + 8 + \frac{200}{Q}\)</span></p></li>
</ol>
</section>
<section id="section-15" class="level3" data-number="7.4.3">
<h3 data-number="7.4.3" class="anchored" data-anchor-id="section-15"><span class="header-section-number">7.4.3</span> :</h3>
<p>&nbsp; Imagine una empresa que vende parrillas. En su primer año vende 752 unidades, a un precio de $279 cada una. Para conocer su elasticidad, el segundo año de operación venden las mismas parrillas a $300 cada una, logrando vender 673 en total. ¿Cuál es su elasticidad de la demanda? ¿Qué puede decir sobre este bien?</p>
<p>&nbsp; <strong>RESPUESTA:</strong></p>
<p>&nbsp; Para calcular la elasticidad de la demanda, es necesario saber la variación de la cantidad demandada respecto al precio. P y Q se reemplazan por los precios y cantidades promedio de los dos años. <span class="math inline">\(\epsilon = \frac{\vartriangle Q}{\vartriangle P} \cdot \frac{P}{Q}\)</span>. Reemplazando quedaría de la siguiente forma: \ <span class="math display">\[\epsilon = \frac{752 - 673}{300 - 279} \cdot \frac{289,5}{712,5} = \frac{79}{21} \cdot \frac{289,5}{712,5} = 1,5\]</span> &nbsp; Al obtener <span class="math inline">\(\epsilon &gt; 1\)</span>, sabemos que estamos frente a una demanda elástica, y como también <span class="math inline">\(\epsilon &gt; 0\)</span>, sabemos que es un bien normal.</p>
</section>
<section id="section-16" class="level3" data-number="7.4.4">
<h3 data-number="7.4.4" class="anchored" data-anchor-id="section-16"><span class="header-section-number">7.4.4</span> :</h3>
<p>Sean <span class="math inline">\(Q_s = \frac{100.000}{3} P\)</span> y <span class="math inline">\(Q_d = 300.000 - \frac{100.000}{3} P\)</span>, las respectivas curvas de oferta y demanda de un bien. Considere que el gobierno quiere reducir su consumo en <span class="math inline">\(\frac{1}{3}\)</span>. Para eso decide gravar la producción con un impuesto por unidad vendida.</p>
<ol type="a">
<li><p>Calcule de cuanto debe ser el impuesto <span class="math inline">\(\tau\)</span> para lograr su objetivo.</p></li>
<li><p>Si quieren lograr lo mismo pero a través de fijación de precios. ¿A cuanto deberían fijarlo? ¿Sería precio máximo o mínimo?</p></li>
</ol>
<p>&nbsp; <strong>RESPUESTAS:</strong></p>
<ol type="a">
<li></li>
</ol>
<p>&nbsp; Para calcular el impuesto primero es necesario calcular el equilibrio sin intervención. Se obtiene el equilibrio <span class="math inline">\(P = 4,5\)</span> y <span class="math inline">\(Q = 150.000\)</span>.</p>
<p>&nbsp; Al reducir la cantidad en <span class="math inline">\(\frac{1}{3}\)</span> queda <span class="math inline">\(Q=100.000\)</span>, por lo que reemplazando ese valor de Q en la curva de demanda tendríamos <span class="math inline">\(P=6\)</span>.</p>
<p>&nbsp; La curva inversa de oferta es <span class="math inline">\(P = \frac{3}{100.000}Q\)</span>, si aplicamos el impuesto <span class="math inline">\(\tau\)</span> la nueva curva queda de la forma: <span class="math display">\[P = \frac{3}{100.000}Q + \tau\]</span></p>
<p>&nbsp; Sustituyendo el punto de equilibrio luego de la reducción en <span class="math inline">\(\frac{1}{3}\)</span> obtenemos <span class="math inline">\(\tau = 3\)</span>.</p>
<ol start="2" type="a">
<li>&nbsp; Si querían fijación de precios en lugar de impuestos debían haber fijado el precio mínimo del bien en 6, lo que no hubiera tenido mucho sentido ya que el equilibrio está por debajo de ese precio.</li>
</ol>
</section>
<section id="section-17" class="level3" data-number="7.4.5">
<h3 data-number="7.4.5" class="anchored" data-anchor-id="section-17"><span class="header-section-number">7.4.5</span> :</h3>
<p>&nbsp; Un grupo de pescadores de la X región se encuentra muy contento durantes estos últimos días. En los periódicos ha aparecido la noticia que el compuesto denominado “f” provoca un aceleramiento en el crecimiento de la anchoveta, un pez característico de la región. La buena noticia es que dicho compuesto es eliminado al mar por la compañía salmonera “Buen Salmón S.A.” al momento de realizar sus procesos de elaboración de salmón enlatado, lo cual ha traído como consecuencia un aumento del número de anchovetas pescadas durante las últimas semanas. Se ha realizado un estudio el cual ha estimado que el impacto positivo de la producción de salmones enlatados sobre la pesca de anchovetas está dada por <span class="math inline">\(f(q) = \frac{bq^2}{4}\)</span> donde “q” es la cantidad de latas producidas por “Buen Salmón SA”. La función de costos de la firma salmonera es <span class="math inline">\(C(q) = a + bq^2\)</span> y la demanda de mercado es <span class="math inline">\(P(q) = a - cq\)</span> Suponga competencia perfecta.</p>
<ol type="a">
<li><p>¿Cuánto produce y a qué precio la firma salmonera</p></li>
<li><p>El encargado de pesca del conglomerado de pescadores atribuye el aumento de la cantidad extraída de anchovetas a su excelente gestión, y en base a esto solicita al grupo un aumento de su sueldo. ¿Se merece el aumento el encargado? Argumente claramente su respuesta</p></li>
<li><p>¿Cuál es el óptimo social de producción de la firma salmonera? Grafique y explique.</p></li>
</ol>
<p>&nbsp; <strong>RESPUESTAS:</strong></p>
<p>&nbsp; Se tiene que: <span class="math display">\[f_{(q)}=\frac{bq^{2}}{4}\]</span> &nbsp; Esta ecuación representa el valor que se le da a la externalidad. La siguente función representa los costos totales</p>
<p><span class="math display">\[C_{(q)}= a + bq^{2}\]</span></p>
<p>&nbsp; Sigue que,</p>
<ol type="a">
<li></li>
</ol>
<p>&nbsp; En competencia perfecta <span class="math display">\[P = Cmg\]</span> <span class="math display">\[a - cq = 2bq\]</span> <span class="math display">\[Q=\frac{a}{2b+c}\]</span> <span class="math display">\[P=\frac{2ab}{2b+c}\]</span></p>
<ol start="2" type="a">
<li><p>&nbsp; No merece el aumento, ya que el incremento de la extracción de anchovetas no se debe a su gestión, sino a la externalidad positiva que genera la empresa.</p></li>
<li></li>
</ol>
<p><span class="math display">\[C_{(q)}= a + bq^{2}-\frac{bq^{2}}{4}\]</span> <span class="math display">\[Cmg_{(q)}= 2bq-\frac{{bq}}{2}= \frac{{3bq}}{2}\]</span> &nbsp; y con la condición de competencia perfecta <span class="math display">\[P = Cmg\]</span> <span class="math display">\[a - cq = \frac{{3bq}}{2}\]</span> <span class="math display">\[{q*(\frac{{3b}}{2} + c)} = a \]</span></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="7,8titulo_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="sobre-capítulo-v" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="sobre-capítulo-v"><span class="header-section-number">7.5</span> Sobre capítulo V:</h2>
<section id="section-18" class="level3" data-number="7.5.1">
<h3 data-number="7.5.1" class="anchored" data-anchor-id="section-18"><span class="header-section-number">7.5.1</span> :</h3>
<p>&nbsp; En una economía, sólo se producen celulares y computadores. En la cuál se produjo lo siguiente en los años 2016, 2017 y 2018:</p>
<p>&nbsp; <strong>RESPUESTAS:</strong></p>
<ol type="1">
<li>Calcular el PIB nominal para los años 2016, 2017, 2018.</li>
</ol>
<p>&nbsp; Recordar que el PIB nominal se calcula con: <span class="math display">\[
\sum q\cdot p
\]</span></p>
<p>&nbsp; Dado esto tenemos:</p>
<p>&nbsp; Para el año 2016: <span class="math display">\[
150\cdot 100 + 100 \cdot 50 = 40000
\]</span></p>
<p>&nbsp; Para el año 2017: <span class="math display">\[
200\cdot 200 + 120 \cdot 70 = 48400
\]</span></p>
<p>&nbsp; Para el año 2018: <span class="math display">\[
250\cdot 300 + 150 \cdot 100 = 90000
\]</span></p>
<ol start="2" type="1">
<li>Calcular el PIB real para los mismos años utilizando como año base el 2016.</li>
</ol>
<p>&nbsp; Recordar que el PIB real se calcula con: <span class="math display">\[
\sum q_t\cdot p_{\text{año base}}
\]</span></p>
<p>&nbsp; Dado esto tenemos:</p>
<p>&nbsp; Para el año 2016:</p>
<p><span class="math display">\[
150\cdot 100 + 100 \cdot 50 = 40000
\]</span></p>
<p>&nbsp; Para el año 2017:</p>
<p><span class="math display">\[
150\cdot 200 + 100 \cdot 70 = 37000
\]</span></p>
<p>&nbsp; Para el año 2018:</p>
<p><span class="math display">\[
150\cdot 300 + 100 \cdot 100 = 55000
\]</span></p>
<ol start="3" type="1">
<li>Calcular el deflactor del PIB para los tres años mencionados anteriormente.</li>
</ol>
<p>&nbsp; Recordar que el deflactor del PIB se calcula con: <span class="math display">\[
\frac{\text{PIB nominal}}{\text{PIB real}}
\]</span></p>
<p>&nbsp; Para el año 2016: <span class="math display">\[
\frac{40000}{40000}=1
\]</span></p>
<p>&nbsp; Para el año 2017: <span class="math display">\[
\frac{48400}{37000}=1.3
\]</span></p>
<p>&nbsp; Para el año 2018: <span class="math display">\[
\frac{90000}{55000}=1.63
\]</span></p>
<ol start="4" type="1">
<li>Calcular la tasa de inflación del mercado, utilizando el año 2016 como base.</li>
</ol>
<p>&nbsp; Recordar que la tasa de inflación anual en los distintos años se calula con: <span class="math display">\[
\frac{Def_{t}}{Def_{t-1}}-1
\]</span></p>
<p>&nbsp; Para el año 2016: <span class="math display">\[
0\%
\]</span></p>
<p>&nbsp; Para el año 2017: <span class="math display">\[
\frac{1.3}{1}-1=30\%
\]</span> Para el año 2018: <span class="math display">\[
\frac{1.63}{1.3}-1=25\%
\]</span></p>
</section>
<section id="section-19" class="level3" data-number="7.5.2">
<h3 data-number="7.5.2" class="anchored" data-anchor-id="section-19"><span class="header-section-number">7.5.2</span> :</h3>
<p>Preguntas de concepto:</p>
<ol type="a">
<li><p>Si los precios no cambian durante un periodo dado, el PIB nominal y el PIB real deberían coincidir. ¿Verdadero o falso?</p></li>
<li><p>Un aumento en la población total va a aumentar el PIB per cápita de un país. ¿Verdadero o falso?</p></li>
<li><p>El PIB es una medida perfecta del bienestar de las personas. ¿Verdadero o falso?</p></li>
</ol>
<p>&nbsp; <strong>RESPUESTAS:</strong></p>
<ol type="a">
<li></li>
</ol>
<p>&nbsp; VERDADERO. Ambas medidas incluyen cantidad y precio, pero el PIB real toma el precio de un periodo determinado, y el PIB nominal toma en cuenta el precio corriente. Si los precios no cambian entre el periodo de referencia del PIB real y el periodo corriente, entonces ambos coinciden.</p>
<ol start="2" type="a">
<li></li>
</ol>
<p>&nbsp; FALSO. No necesariamente. Considerando que el <span class="math inline">\(PIB_{pc}=PIB/(Población Total)\)</span> es posible afirmar que un aumento en la población total va a traer como consecuencia una disminución en el PIB pc de un país. Siempre y cuando el PIB se mantenga constante.</p>
<ol start="3" type="a">
<li></li>
</ol>
<p>&nbsp; FALSO. EL excluye cosas importantes como los tiempos de ocio, los bienes y servicios del hogar y tampoco explica la distribución de riqueza en el país y como ese PIB per capita realmente se destribuye en un ciudadano promedio. Pero, igualmente el PIB es considerado como una buena medida del bienestar económico ya que existe una correlación fuerte entre aquellos países con PIB alto y buena salud, educación, innovación, entre otros.</p>
</section>
<section id="section-20" class="level3" data-number="7.5.3">
<h3 data-number="7.5.3" class="anchored" data-anchor-id="section-20"><span class="header-section-number">7.5.3</span> :</h3>
<p>&nbsp; En un país imaginario, la canasta básica es considerada como 2 kilos de queso, 2 pares de jeans y 10 litros de bencina.</p>
<ol type="a">
<li>Con esa información complete la siguiente tabla:</li>
</ol>
<div>




    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            border: 1px solid black;
            padding: 8px;
            text-align: left;
        }
    </style>




    
<table data-quarto-postprocess="true" class="table">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th"></td>
<td data-quarto-table-cell-role="th"></td>
<td colspan="2" data-quarto-table-cell-role="th">Año 1</td>
<td colspan="2" data-quarto-table-cell-role="th">Año 2</td>
<td colspan="2" data-quarto-table-cell-role="th">Año 3</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Items Canasta</td>
<td data-quarto-table-cell-role="th">Unidades</td>
<td data-quarto-table-cell-role="th">$ unidad</td>
<td data-quarto-table-cell-role="th">$ Total</td>
<td data-quarto-table-cell-role="th">$ unidad</td>
<td data-quarto-table-cell-role="th">$ Total</td>
<td data-quarto-table-cell-role="th">$ unidad</td>
<td data-quarto-table-cell-role="th">$ total</td>
</tr>
<tr class="odd">
<td>Queso</td>
<td>2 kg</td>
<td>5000</td>
<td></td>
<td>5132</td>
<td></td>
<td>5500</td>
<td></td>
</tr>
<tr class="even">
<td>Jeans</td>
<td>2 pares</td>
<td>20000</td>
<td></td>
<td>25000</td>
<td></td>
<td>30000</td>
<td></td>
</tr>
<tr class="odd">
<td>Bencina</td>
<td>10 litros</td>
<td>890</td>
<td></td>
<td>1100</td>
<td></td>
<td>1200</td>
<td></td>
</tr>
<tr class="even">
<td>Costo Total</td>
<td></td>
<td>34,8</td>
<td></td>
<td>154</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>





</div>
<ol start="2" type="a">
<li><p>Calcule el IPC para cada año, eligiendo el año 1 como base.</p></li>
<li><p>Utilizando el IPC calcule la tasa de inflación para cada año.</p></li>
</ol>
<p>&nbsp; <strong>RESPUESTAS:</strong></p>
<ol type="a">
<li></li>
</ol>
<div>




    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            border: 1px solid black;
            padding: 8px;
            text-align: left;
        }
    </style>




    
<table data-quarto-postprocess="true" class="table">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th"></td>
<td data-quarto-table-cell-role="th"></td>
<td colspan="2" data-quarto-table-cell-role="th">Año 1</td>
<td colspan="2" data-quarto-table-cell-role="th">Año 2</td>
<td colspan="2" data-quarto-table-cell-role="th">Año 3</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Items Canasta</td>
<td data-quarto-table-cell-role="th">Unidades</td>
<td data-quarto-table-cell-role="th">$ unidad</td>
<td data-quarto-table-cell-role="th">$ Total</td>
<td data-quarto-table-cell-role="th">$ unidad</td>
<td data-quarto-table-cell-role="th">$ Total</td>
<td data-quarto-table-cell-role="th">$ unidad</td>
<td data-quarto-table-cell-role="th">$ total</td>
</tr>
<tr class="odd">
<td>Queso</td>
<td>2 kg</td>
<td>5000</td>
<td>10000</td>
<td>5132</td>
<td>10264</td>
<td>5500</td>
<td>11000</td>
</tr>
<tr class="even">
<td>Jeans</td>
<td>2 pares</td>
<td>20000</td>
<td>40000</td>
<td>25000</td>
<td>50000</td>
<td>30000</td>
<td>60000</td>
</tr>
<tr class="odd">
<td>Bencina</td>
<td>10 litros</td>
<td>890</td>
<td>8900</td>
<td>1100</td>
<td>11000</td>
<td>1200</td>
<td>12000</td>
</tr>
<tr class="even">
<td>Costo Total</td>
<td></td>
<td></td>
<td>58900</td>
<td></td>
<td>71264</td>
<td></td>
<td>83000</td>
</tr>
</tbody>
</table>





</div>
<ol start="2" type="a">
<li></li>
</ol>
<p>&nbsp; El Índice Precio al Consumidor es una medida del costo total de los bienes y servicios comprados por un consumidor típico.</p>
<p>&nbsp; Año 1 <span class="math display">\[IPC = \frac{58900}{58900}*100= \%100\]</span></p>
<p>&nbsp; Año 2 <span class="math display">\[IPC = \frac{71264}{58900}*100=\%120.99\]</span></p>
<p>&nbsp; Año 3 <span class="math display">\[IPC = \frac{83000}{58900}*100=\%140.90\]</span></p>
<ol start="3" type="a">
<li></li>
</ol>
<p>&nbsp; La tasa de inflación es el cambio porcentual en el índice de precios con respecto al periodo precedente.</p>
<p>&nbsp; Año 1 <span class="math display">\[IPC = \frac{100-100}{100}*100= \%0\]</span></p>
<p>&nbsp; Año 2 <span class="math display">\[IPC = \frac{120.99-100}{100}*100=\%20.99\]</span></p>
<p>&nbsp; Año 3 <span class="math display">\[IPC = \frac{140.90-120.99}{120.99}*100=\%16.45\]</span></p>
</section>
<section id="section-21" class="level3" data-number="7.5.4">
<h3 data-number="7.5.4" class="anchored" data-anchor-id="section-21"><span class="header-section-number">7.5.4</span> :</h3>
<ol type="a">
<li>Un país tiene solo los mercados de la siguiente tabla:</li>
</ol>
<div>




    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            border: 1px solid black;
            padding: 8px;
            text-align: left;
        }
    </style>




    
<table data-quarto-postprocess="true" class="table">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Rubro</td>
<td data-quarto-table-cell-role="th">Cantidad producida</td>
<td data-quarto-table-cell-role="th">Valor por unidad</td>
</tr>
<tr class="even">
<td>Venta de autos importados</td>
<td>20</td>
<td>$120</td>
</tr>
<tr class="odd">
<td>Producción de harina para mercados nacionales</td>
<td>400</td>
<td>$10</td>
</tr>
<tr class="even">
<td>Producción minera</td>
<td>1000</td>
<td>$80</td>
</tr>
<tr class="odd">
<td>Producción de harina para exportaciones</td>
<td>1200</td>
<td>$15</td>
</tr>
</tbody>
</table>





</div>
<p>&nbsp; Indique cuanto es la cantidad del PIB.</p>
<ol start="2" type="a">
<li>Sin tomar en cuenta la pregunta anterior, tenemos otro país con los siguientes datos:</li>
</ol>
<div>




    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            border: 1px solid black;
            padding: 8px;
            text-align: left;
        }
    </style>




    
<table data-quarto-postprocess="true" class="table">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Año</td>
<td data-quarto-table-cell-role="th">PIB nominal</td>
<td data-quarto-table-cell-role="th">PIB real</td>
</tr>
<tr class="even">
<td>Actual</td>
<td>$30</td>
<td>$31</td>
</tr>
<tr class="odd">
<td>Base</td>
<td>$25</td>
<td>$30</td>
</tr>
</tbody>
</table>





</div>
<p>&nbsp; Calcule su Inflación por el deflactor del PIB.</p>
<p>&nbsp; <strong>RESPUESTAS:</strong></p>
<ol type="a">
<li></li>
</ol>
<p>&nbsp; De todos los rubros el unico que no pertenece a la categoría del PIB es la venta de autos importados. Por los demás, se multiplica la unidad por su valor y se suma con el resto.</p>
<p><span class="math display">\[400\cdot10+1000\cdot80+1200\cdot15=102000\]</span></p>
<ol start="2" type="a">
<li></li>
</ol>
<p>&nbsp; Primero calculamos los deflactores:</p>
<p>&nbsp; Para el actual: <span class="math inline">\(30/31\)</span>.</p>
<p>&nbsp; Para el base: <span class="math inline">\(5/6\)</span></p>
<p>&nbsp; Luego calculamos la inflación:</p>
<p><span class="math display">\[Inflación:\frac{\frac{30}{31}-\frac{5}{6}}{\frac{5}{6}}=\frac{36}{31}-1=\frac{5}{31}=\%16.13\]</span></p>
</section>
<section id="section-22" class="level3" data-number="7.5.5">
<h3 data-number="7.5.5" class="anchored" data-anchor-id="section-22"><span class="header-section-number">7.5.5</span> :</h3>
<p>&nbsp; Suponga un mercado con las siguientes funciones de oferta y demanda laboral: <span class="math display">\[L_s=10+10w\]</span> <span class="math display">\[L_d=100-5w\]</span></p>
<ol type="a">
<li><p>Encuentre el nivel de equilibrio.</p></li>
<li><p>Suponga la fijación de un salario igual a 10 y determine que pasará en ese mercado.</p></li>
</ol>
<p>&nbsp; <strong>RESPUESTA:</strong></p>
<p>&nbsp; Para resolver esto primero debemos encontrar el equilibrio, lo cual nos da <span class="math inline">\(L = 70\)</span> y <span class="math inline">\(w = 6\)</span>. &nbsp; Si reemplazamos el salario mínimo impuesto en ambas funciones, vemos que la demanda de trabajo sería <span class="math inline">\(L_d=50\)</span> y la oferta <span class="math inline">\(L_s=100\)</span>. Es decir, habrían 110 personas dispuestas a trabajar y sólo 50 puestos demandados. El desempleo sería: <span class="math display">\[L_s - L_d = 110 - 50 = 60\]</span></p>
</section>
<section id="section-23" class="level3" data-number="7.5.6">
<h3 data-number="7.5.6" class="anchored" data-anchor-id="section-23"><span class="header-section-number">7.5.6</span> :</h3>
<p>&nbsp; El 2014 es el año base para el cálculo del ́Índice de Precios al Consumidor. A partir de la siguiente tabla calcule:</p>
<div>




    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            border: 1px solid black;
            padding: 8px;
            text-align: left;
        }
    </style>




    
<table data-quarto-postprocess="true" class="table">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th"></td>
<td data-quarto-table-cell-role="th">2014</td>
<td data-quarto-table-cell-role="th">2015</td>
<td data-quarto-table-cell-role="th">2016</td>
</tr>
<tr class="even">
<td>Precio de celular</td>
<td>$800.000</td>
<td>$820.000</td>
<td>$850.000</td>
</tr>
<tr class="odd">
<td>Precio del tomate</td>
<td>$300</td>
<td>$450</td>
<td>$500</td>
</tr>
<tr class="even">
<td>Precio de zapatos</td>
<td>$50.000</td>
<td>$45.000</td>
<td>$55.000</td>
</tr>
<tr class="odd">
<td>Cantidad de celular</td>
<td>1</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td>Cantidad del tomate</td>
<td>200</td>
<td>200</td>
<td>200</td>
</tr>
<tr class="odd">
<td>Cantidad de zapatos</td>
<td>4</td>
<td>4</td>
<td>4</td>
</tr>
</tbody>
</table>





</div>
<ol type="a">
<li><p>El ́Índice de Precios al Consumidor para cada año (2014, 2015 y 2016).</p></li>
<li><p>Calcule la inflación (variación de precios) anual 2015-2016 y 2014-2015.</p></li>
<li><p>Ahora usted le presta <span class="math inline">\(30.000\)</span> a su amigo, quien se compromete a devolver <span class="math inline">\(32.000\)</span> al cabo de un año, en este caso el 31 de diciembre de 2016.</p></li>
</ol>
<ul>
<li><p>¿Cuál es la tasa de interés nominal que su amigo está dispuesto a pagarle?</p></li>
<li><p>¿Cuál es la tasa de interés real? Nota: Tenga en cuenta la inflación anual 2015-2016</p></li>
</ul>
<ol start="4" type="a">
<li>Ahora suponga que usted le presta a su amigo en UF. Cuando usted le prestó el dinero a su amigo, la UF era de <span class="math inline">\(25.000\)</span>. Si su amigo se compromete a pagarle la misma tasa de interés nominal del ejercicio anterior y devolverle el dinero un año después, ¿cuánto dinero recibe usted al cabo de un año?</li>
</ol>
<p>&nbsp; <strong>RESPUESTAS:</strong></p>
<ol type="a">
<li></li>
</ol>
<p><span class="math display">\[\textbf{Costo de vida 2014} = 800.000*1+300*200+50.000*4 = 1.060.000\]</span> <span class="math display">\[\textbf{Costo de vida 2015} = 820.000*1+450*200+45.000*4 = 1.090.000\]</span> <span class="math display">\[\textbf{Costo de vida 2016} = 850.000*1+500*200+55.000*4 = 1.170.000\]</span></p>
<p><span class="math display">\[IPC_{2014} = \frac{1.060.000}{(1.060.000)*100} = 100\]</span> <span class="math display">\[IPC_{2015} = \frac{1.090.000}{(1.060.000)*100} = 102.8\]</span> <span class="math display">\[IPC_{2016} = \frac{1.170.000}{(1.060.000)*100} = 110.4\]</span></p>
<ol start="2" type="a">
<li></li>
</ol>
<p><span class="math display">\[\textbf{Variación Precios 2015/2014} = (\frac{ 102.8}{100}-1)*100 = 2,83 \%\]</span> <span class="math display">\[\textbf{Variación Precios 2016/2015} = (\frac{110.4}{102.8}-1)*100 = 7.34 \%\]</span></p>
<ol start="3" type="a">
<li></li>
</ol>
<p>&nbsp; La tasa de interés nominal que su amigo estará pagando será la relación entre lo prestado y lo que finalmente le pagará.</p>
<p>&nbsp; <strong>Tasa de interés nominal</strong> = <span class="math inline">\((\frac{32000}{30000}– 1)\cdot 100 = 6.66\%\)</span></p>
<p>&nbsp; La tasa de interés real representa cuanto realmente estarás ganado al prestarle dinero a tu amigo. Ya que aunque la tasa de interés nominal es mayor a 0, si la tasa de inflación de ese año será mayor o igual a la nominal, no existe una ganacia real en ese préstamo.</p>
<p>&nbsp; <strong>Tasa de interés real</strong> = <strong>tasa de interés nominal</strong> – <strong>inflación</strong> &nbsp; <strong>Tasa de interés real</strong> = <span class="math inline">\(6.66 – 7.34 = -0.68\%\)</span></p>
<p>&nbsp; Debido a que la tasa de inflación es real a la nominal, al hacer este préstamo, el valor de tu dinero disminuye.</p>
<ol start="4" type="a">
<li></li>
</ol>
<p><strong>Prestamo en UF</strong> = <span class="math inline">\(\frac{30,000}{25,000} = 1.2 UF\)</span> <strong>Pago en un año</strong> = <span class="math inline">\(1.2\times(1 + 6.66 \%) = 1.28\)</span> <strong>En un año la UF</strong> = <span class="math inline">\(25,000\times(1 + 7.34 \%) = 26,834.9\)</span> <strong>Pago efectivo</strong> = <span class="math inline">\(1.28\times26,834.9 = 34,348.5\)</span></p>
</section>
<section id="section-24" class="level3" data-number="7.5.7">
<h3 data-number="7.5.7" class="anchored" data-anchor-id="section-24"><span class="header-section-number">7.5.7</span> :</h3>
<p>&nbsp; Tenemos la siguiente tabla que representa el porcentaje de población acumulado de la población según su ingreso porcentual acumulado:</p>
<div>



    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tabla de Demanda</title>
    <style>
        table {
            border-collapse: collapse;
            width: 50%;
            margin: 20px auto;
        }

        th, td {
            border: 1px solid black;
            padding: 8px;
            text-align: center;
        }

        th {
            background-color: #f2f2f2;
        }
    </style>


    
<table data-quarto-postprocess="true" class="table">
<caption>Tabla de demanda:</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">decil:</td>
<td data-quarto-table-cell-role="th">Ingresos:</td>
</tr>
<tr class="even">
<td>0.1</td>
<td>0.01</td>
</tr>
<tr class="odd">
<td>0.2</td>
<td>0.02</td>
</tr>
<tr class="even">
<td>0.3</td>
<td>0.03</td>
</tr>
<tr class="odd">
<td>0.4</td>
<td>0.05</td>
</tr>
<tr class="even">
<td>0.5</td>
<td>0.06</td>
</tr>
<tr class="odd">
<td>0.6</td>
<td>0.08</td>
</tr>
<tr class="even">
<td>0.7</td>
<td>0.14</td>
</tr>
<tr class="odd">
<td>0.8</td>
<td>0.58</td>
</tr>
<tr class="even">
<td>0.9</td>
<td>0.80</td>
</tr>
<tr class="odd">
<td>1</td>
<td>1</td>
</tr>
</tbody>
</table>



</div>
<p>&nbsp; Calcule el coeficiente de Ginni.</p>
<p>&nbsp; <strong>RESPUESTA:</strong></p>
<p><span class="math display">\[G=1-\left|\sum_{k=0}^{n-1}\left(X_{k+1}-X_k\right)\left(Y_{k+1}+Y_k\right)\right| \]</span></p>
<p><span class="math display">\[1-0.1(0.01+(0.01+0.02)+(0.02+0.03)+(0.03+0.05)+(0.05+0.06)+(0.06+0.08))+\]</span> <span class="math display">\[0.1((0.08+0.10)+(0.10+0.50)+(0.50+0.8)+(0.8+1))\]</span> <span class="math display">\[=\]</span> <span class="math display">\[1-0.1\cdot 4.3\]</span> <span class="math display">\[1-0.43\]</span> <span class="math display">\[0.57\]</span></p>
</section>
<section id="section-25" class="level3" data-number="7.5.8">
<h3 data-number="7.5.8" class="anchored" data-anchor-id="section-25"><span class="header-section-number">7.5.8</span> :</h3>
<p>&nbsp; Suponga que tanto las papas fritas como el ketchup son mercados monopólicos. Las funciones de costo total son, respectivamente <span class="math inline">\(CT_{PF}=10\cdot q_{PF}\)</span> y <span class="math inline">\(CT_{K}=5\cdot q_{K}\)</span> &nbsp; Las demandas respectivas se pueden expresar como: <span class="math inline">\(P_{PF}=100 - q_{PF}\)</span> y <span class="math inline">\(P_{K}= 80 - q_{K} + q_{PF}\)</span>. Si es que cada bien es producido por monopolistas separados, determine los precios y cantidades de cada uno.</p>
<p>&nbsp; <strong>RESPUESTA:</strong></p>
<p>&nbsp; El monopolista de papas fritas produce una cantidad de papas fritas tal que maximicen su utilidad:</p>
<p><span class="math display">\[\pi_{PF}= P_{PF}\cdot q_{PF} - CT_{PF}\]</span> <span class="math display">\[\pi_{PF}= (100 - q_{PF})\cdot q_{PF} - 10\cdot q_{PF}\]</span> <span class="math display">\[ pdv = \frac{\pi_{PF}}{q_{PF}}=0= 100-2\cdot q_{PF} - 10\]</span> <span class="math display">\[q_{PF} = 45\]</span> <span class="math display">\[P_{PF} = 55\]</span></p>
<p>&nbsp; Con este resultado, podemos encontrar el óptimo del monopolista del ketchup\</p>
<p><span class="math display">\[\pi_{K}= P_{K}\cdot q_{K} - CT_{K}\]</span> <span class="math display">\[\pi_{K}= (80 - q_{K} + q_{PF} )\cdot q_{K} - 5\cdot q_{K}\]</span> <span class="math display">\[\pi_{K}= 80\cdot q_{K} - q_{K}^2 + q_{PF}\cdot q_{K} - 5\cdot q_{K}\]</span> <span class="math display">\[\pi_{K}= 80\cdot q_{K} - q_{K}^2 + 45\cdot q_{K}  - 5\cdot q_{K}\]</span> <span class="math display">\[\pi_{K}= 120\cdot q_{K} - q_{K}^2\]</span> <span class="math display">\[pdv = \frac{\pi_{K}}{q_{K}}=0= 120-2\cdot q_{K}\]</span> <span class="math display">\[q_{K} = 60\]</span> <span class="math display">\[P_{K} = 65\]</span></p>
</section>
<section id="section-26" class="level3" data-number="7.5.9">
<h3 data-number="7.5.9" class="anchored" data-anchor-id="section-26"><span class="header-section-number">7.5.9</span> :</h3>
<p>&nbsp; Suponga que tanto las papas fritas como el ketchup son mercados monopólicos. Las funciones de costo total son, respectivamente <span class="math inline">\(CT_{PF}=10\cdot q_{PF}\)</span> y <span class="math inline">\(CT_{K}=5\cdot q_{K}\)</span>\ Las demandas respectivas se pueden expresar como: <span class="math inline">\(P_{PF}=100 - q_{PF}\)</span> y <span class="math inline">\(P_{K}= 80 - q_{K} + q_{PF}\)</span></p>
<ol type="a">
<li><p>Si es que cada bien es producido por monopolistas separados, determine los precios y cantidades de cada uno.</p></li>
<li><p>Asuma ahora que ambas empresas desean integrarse en una sola y monopólica, determine los precios y cantidades para cada bien.\</p></li>
<li><p>¿Cuál es mejor desde un punto de vista social? ¿Por qué?</p></li>
</ol>
<p>&nbsp; <strong>RESPUESTAS:</strong></p>
<ol type="a">
<li></li>
</ol>
<p>&nbsp; El monopolista de papas fritas produce una cantidad de papas fritas tal que maximicen su utilidad:</p>
<p><span class="math display">\[\pi_{PF}= P_{PF}\cdot q_{PF} - CT_{PF}\]</span> <span class="math display">\[\pi_{PF}= (100 - q_{PF})\cdot q_{PF} - 10\cdot q_{PF}\]</span> <span class="math display">\[pdv {\pi_{PF}}{q_{PF}}=0= 100-2\cdot q_{PF} - 10\]</span> <span class="math display">\[q_{PF} = 45\]</span> <span class="math display">\[P_{PF} = 55\]</span></p>
<p>&nbsp; Con este resultado, podemos encontrar el óptimo del monopolista del ketchup.</p>
<p><span class="math display">\[\pi_{K}= P_{K}\cdot q_{K} - CT_{K}\]</span> <span class="math display">\[\pi_{K}= (80 - q_{K} + q_{PF} )\cdot q_{K} - 5\cdot q_{K}\]</span> <span class="math display">\[\pi_{K}= 80\cdot q_{K} - q_{K}^2 + q_{PF}\cdot q_{K} - 5\cdot q_{K}\]</span> <span class="math display">\[\pi_{K}= 80\cdot q_{K} - q_{K}^2 + 45\cdot q_{K}  - 5\cdot q_{K}\]</span> <span class="math display">\[\pi_{K}= 120\cdot q_{K} - q_{K}^2\]</span> <span class="math display">\[pdv {\pi_{K}}{q_{K}}=0= 120-2\cdot q_{K}\]</span> <span class="math display">\[q_{K} = 60\]</span> <span class="math display">\[P_{K} = 65\]</span></p>
<ol start="2" type="a">
<li></li>
</ol>
<p>&nbsp; Si ambos bienes se producen por sólo uno de los monopolistas, entonces el problema que enfrenta ahora es:</p>
<p><span class="math display">\[\pi= P_{PF}\cdot q_{PF} + P_{K}\cdot q_{K} - CT_{K} - CT_{PF}\]</span> <span class="math display">\[\pi= (100 - q_{PF})\cdot q_{PF} + (80 - q_{K} + q_{PF} )\cdot q_{K} - 10\cdot q_{PF} - 5\cdot q_{K}\]</span> <span class="math display">\[\pi= 100\cdot q_{PF} - q_{PF}^2 + 80\cdot q_{K} - q_{K}^2  +q_{PF}\cdot q_{K} - 10\cdot q_{PF} - 5\cdot q_{K}\]</span> <span class="math display">\[\pi= 90\cdot q_{PF} +  75\cdot q_{K} + q_{PF}\cdot q_{K} - q_{PF}^2 - q_{K}^2 \]</span></p>
<p><span class="math display">\[pdv {\pi}{q_{PF}}=0= 90 + q_{K} - 2\cdot q_{PF}\]</span> <span class="math display">\[pdv {\pi}{q_{K}}=0= 75 + q_{PF} - 2\cdot q_{K}\]</span></p>
<p><span class="math display">\[q_{PF} = \frac{255}{3}= 85\]</span> <span class="math display">\[q_{K} = 80\]</span> <span class="math display">\[P_{PF} = 15\]</span> <span class="math display">\[P_{K} = 65\]</span></p>
<ol start="3" type="a">
<li>¿Cuál es mejor desde un punto de vista social? ¿Por qué?</li>
</ol>
<p><span class="math display">\[BS_{Integrado}= EP_{Integrado} +EC_{Integrado}  \]</span> <span class="math display">\[EP_{Integrado}= 85\cdot 15 - 85\cdot 10 + 100\cdot 65 -100\cdot 5 = 6425   \]</span> <span class="math display">\[EC_{Integrado}= \frac{85\cdot 85}{2}  +\frac{100\cdot 100}{2}  = 8612.5\]</span> <span class="math display">\[BS_{Integrado}= 15037.5 \]</span></p>
<p><span class="math display">\[BS_{PF} = EP_{PF} + EC_{PF} =55\cdot45 -45\cdot10 +  \frac{45\cdot 45}{2} = 3037.5\]</span></p>
<p><span class="math display">\[BS_{K} = EP_{K} + EC_{K} = 60\cdot65 -60\cdot5 +  \frac{60\cdot 60}{2} = 5400\]</span></p>
<p><span class="math display">\[BS_{Integrado}= 8437.5 \]</span></p>
<p>&nbsp; La integración de ambos monopolios es positiva desde el punto de vista social. Esto se debe a que ambos productos son complementarios</p>
<p>###:</p>
<p>&nbsp; Considere una economía en la cual se tiene el siguiente detalle de los bienes producidos o importados por sus habitantes.</p>
<div>



    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tabla</title>




<table data-quarto-postprocess="true" class="table">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="border: 1px solid black; padding: 8px">Bien</td>
<td data-quarto-table-cell-role="th" style="border: 1px solid black; padding: 8px">Categoria</td>
</tr>
<tr class="even">
<td style="border: 1px solid black; padding: 8px">Pan</td>
<td style="border: 1px solid black; padding: 8px">Producido</td>
</tr>
<tr class="odd">
<td style="border: 1px solid black; padding: 8px">Vino</td>
<td style="border: 1px solid black; padding: 8px">Producido</td>
</tr>
<tr class="even">
<td style="border: 1px solid black; padding: 8px">Autos</td>
<td style="border: 1px solid black; padding: 8px">Importado</td>
</tr>
<tr class="odd">
<td style="border: 1px solid black; padding: 8px">Cobre</td>
<td style="border: 1px solid black; padding: 8px">Producido</td>
</tr>
</tbody>
</table>




</div>
<ol type="a">
<li><p>¿Cuáles son los bienes que se consideran para el cálculo del pib?\</p></li>
<li><p>¿Cuáles son los bienes que se consideran para el cálculo del IPC?\</p></li>
</ol>
<p>c)¿ Por qué la inflación difiere cuando se usa el Deflactor o el IPC ?\</p>
<p>&nbsp; <strong>RESPUESTAS:</strong></p>
<ol type="a">
<li></li>
</ol>
<p>Solo se consideran los bienes producidos: Pan,Vino y Cobre\</p>
<ol start="2" type="a">
<li></li>
</ol>
<p>&nbsp; Ahora se considera el bien “Autos” ya que es un bien dentro de la canasta de consumo, pero no se considera el bien “Cobre” puesto que no es consumido</p>
<ol start="3" type="a">
<li></li>
</ol>
<p>&nbsp; La inflación difiere cuando se usa el Deflactor o el IPC porque ambos indicadores miden cosas distintas. El Deflactor considera todos los bienes producidos dentro de la economía, los cuales no todos son necesariamente consumidos por las personas. Por lo tanto, si se quiere analizar el costo de la vida, es mejor usar el IPC para medir la inflación dado que en el IPC se usa una canasta de consumo representativa. Con respecto a críticas de ambas formas para medir la inflación, se tiene que al medirla por el lado del Deflactor no se refleja de forma precisa variaciones en el costo de vida. Mientras que una crítica al usar el IPC para medir la inflación es el sesgo de sustitución: el IPC no incorpora el efecto sustitución por el lado de los consumidores cuando sube el precio de un bien dentro de la canasta de consumo.</p>
</section>
<section id="section-27" class="level3" data-number="7.5.10">
<h3 data-number="7.5.10" class="anchored" data-anchor-id="section-27"><span class="header-section-number">7.5.10</span> :</h3>
<p>&nbsp; En el país X se consumen solamente arroz, pantalones y celulares. El arroz y los pantalones son producidos y consumidos en X. Por otro lado, los celulares son importados desde el país Y.</p>
<div>



    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            border: 1px solid black;
            padding: 8px;
            text-align: center;
        }

        th {
            background-color: #f2f2f2;
        }
    </style>




<table data-quarto-postprocess="true" class="table">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th"></td>
<td colspan="2" data-quarto-table-cell-role="th">Año 1</td>
<td colspan="2" data-quarto-table-cell-role="th">Año 2</td>
<td colspan="2" data-quarto-table-cell-role="th">Año 3</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Productos</td>
<td data-quarto-table-cell-role="th">cantidad</td>
<td data-quarto-table-cell-role="th">$ unidad</td>
<td data-quarto-table-cell-role="th">cantidad</td>
<td data-quarto-table-cell-role="th">$ unidad</td>
<td data-quarto-table-cell-role="th">cantidad</td>
<td data-quarto-table-cell-role="th">$ unidad</td>
</tr>
<tr class="odd">
<td>Arroz</td>
<td>160</td>
<td>480</td>
<td>320</td>
<td>158</td>
<td>156</td>
<td>410</td>
</tr>
<tr class="even">
<td>Pantalones</td>
<td>180</td>
<td>435</td>
<td>410</td>
<td>160</td>
<td>652</td>
<td>352</td>
</tr>
<tr class="odd">
<td>Celulares</td>
<td>185</td>
<td>420</td>
<td>420</td>
<td>140</td>
<td>410</td>
<td>586</td>
</tr>
</tbody>
</table>




</div>
<ol type="a">
<li><p>Calcular el PIB Nominal.</p></li>
<li><p>Calcular el PIB Real con el año 2 como base.</p></li>
<li><p>Calcular la tasa de crecimiento del país.</p></li>
<li><p>Calcular el deflactor del PIB para cada año y la tasa de inflación para cada año.</p></li>
</ol>
<p>&nbsp; <strong>RESPUESTAS:</strong></p>
<ol type="a">
<li></li>
</ol>
<p><span class="math display">\[PIB_{1}= 160x480+320x158= 76800+ 50560= 127360\]</span> <span class="math display">\[PIB_{2}= 180x435+410x160= 78300+65600= 143900\]</span> <span class="math display">\[PIB_{3}= 185x420+420x140= 77700+58800= 136500\]</span></p>
<ol start="2" type="a">
<li></li>
</ol>
<p><span class="math display">\[PIBreal_{1}= 160x435+320x160= 69.600+51.200= 120800 \]</span> <span class="math display">\[PIBreal_{2}= 180x435+410x160= 78300+65600= 143900 \]</span> <span class="math display">\[PIBreal_{3}= 185x435+420x160= 80475+ 67200= 147675 \]</span></p>
<ol start="3" type="a">
<li></li>
</ol>
<p><span class="math display">\[Tasa_{año1-2}=\frac{143900 − 120800}{120000}*100 = 19,25 \% \]</span> <span class="math display">\[Tasa_{año2-3}=\frac{147675 − 143900}{143900}*100 = 2,62\% \]</span></p>
<ol start="4" type="a">
<li></li>
</ol>
<p><span class="math display">\[Deflactor_{año1} = \frac{127360}{120800}=1,05\]</span> <span class="math display">\[Deflactor_{año2} = \frac{143900}{143900}=1\]</span> <span class="math display">\[Deflactor_{año3} = \frac{136500}{147675}=0,92\]</span></p>
<p>&nbsp; Inflación: <span class="math display">\[\frac{1 - 1,05}{1,05}*100 = -47,61\%\]</span> <span class="math display">\[\frac{0,92 - 1}{1}*100 = -8 \%\]</span></p>
</section>
<section id="section-28" class="level3" data-number="7.5.11">
<h3 data-number="7.5.11" class="anchored" data-anchor-id="section-28"><span class="header-section-number">7.5.11</span> :</h3>
<p>&nbsp; Tenemos la siguiente tabla que representa el porcentaje de población acumulado de la población según su ingreso porcentual acumulado:</p>
<div>



    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        table {
            border-collapse: collapse;
            width: 50%;
            margin: auto;
        }

        th, td {
            border: 1px solid black;
            padding: 8px;
            text-align: center;
        }

        th {
            background-color: #f2f2f2;
        }
    </style>




<table data-quarto-postprocess="true" class="table">
<caption>Tabla de demanda:</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">decil:</td>
<td data-quarto-table-cell-role="th">Ingresos:</td>
</tr>
<tr class="even">
<td>0.1</td>
<td>0.01</td>
</tr>
<tr class="odd">
<td>0.2</td>
<td>0.02</td>
</tr>
<tr class="even">
<td>0.3</td>
<td>0.03</td>
</tr>
<tr class="odd">
<td>0.4</td>
<td>0.04</td>
</tr>
<tr class="even">
<td>0.5</td>
<td>0.05</td>
</tr>
<tr class="odd">
<td>0.6</td>
<td>0.06</td>
</tr>
<tr class="even">
<td>0.7</td>
<td>0.10</td>
</tr>
<tr class="odd">
<td>0.8</td>
<td>0.15</td>
</tr>
<tr class="even">
<td>0.9</td>
<td>0.20</td>
</tr>
<tr class="odd">
<td>1</td>
<td>1</td>
</tr>
</tbody>
</table>




</div>
<p>&nbsp; Calcule el coeficiente de Ginni.</p>
<p>&nbsp; <strong>RESPUESTA:</strong></p>
<p><span class="math display">\[G=1-\left|\sum_{k=0}^{n-1}\left(X_{k+1}-X_k\right)\left(Y_{k+1}+Y_k\right)\right| \]</span> <span class="math display">\[1-0.1(0.01+(0.01+0.02)+(0.02+0.03)+(0.03+0.04)+(0.04+0.05)+(0.05+0.06))+\]</span> <span class="math display">\[0.1((0.06+0.10)+(0.10+0.15)+(0.15+0.2)+(0.2+1))\]</span> <span class="math display">\[=\]</span> <span class="math display">\[1-0.1\cdot 2.32\]</span> <span class="math display">\[1-0.232\]</span> <span class="math display">\[0.768\]</span></p>
</section>
<section id="section-29" class="level3" data-number="7.5.12">
<h3 data-number="7.5.12" class="anchored" data-anchor-id="section-29"><span class="header-section-number">7.5.12</span> :</h3>
<p>&nbsp; La función de producción es la relación entre la cantidad de insumos utilizados para producir un bien y la cantidad producida de estos.</p>
<p>&nbsp; Una empresa ’’A´´ tiene la siguiente función de producción de kilogramos de jamón:</p>
<p><span class="math display">\[Q = 4KL + K^2 + 0.5L^2\]</span></p>
<p>&nbsp; Y una empresa ’’B´´ tiene esta otra función de producción la misma materia.</p>
<p><span class="math display">\[Q = KL + 2K^2 + L^2\]</span></p>
<p>&nbsp; En el mercado de la empresa, cada unidad producida es vendida por $5 dólares. con :</p>
<ul>
<li><span class="math inline">\(Q\)</span>: cantidad producida.</li>
<li><span class="math inline">\(L\)</span>: unidades de trabajo usadas en la producción (pueden ser horas de trabajo trabajadores) .</li>
<li><span class="math inline">\(K\)</span>: unidades de capital usadas en la producción.</li>
</ul>
<p>&nbsp; Si los trabajadores de ambas empresas trabajan las mismas horas, y se gasta la misma cantidad en horas que en capital usado. ¿Que empresa gasta más en producir el bien?</p>
<p>&nbsp; <strong>RESPUESTA:</strong> <span class="math display">\[L=K=X\]</span></p>
<p>&nbsp; Empresa B:</p>
<p><span class="math display">\[Q = X^2 + 2X^2 + X^2\]</span> <span class="math display">\[Q = 4X^2\]</span></p>
<p>&nbsp; Empresa A:</p>
<p><span class="math display">\[Q = 4X^2 + X^2 + 0.5X^2\]</span> <span class="math display">\[Q = 5.5X^2\]</span></p>
<p><span class="math display">\[5.5X^2 &gt; 4X^2\]</span></p>
<p>&nbsp; Entonces la empresa A, produce más caro que la empresa B</p>
</section>
<section id="section-30" class="level3" data-number="7.5.13">
<h3 data-number="7.5.13" class="anchored" data-anchor-id="section-30"><span class="header-section-number">7.5.13</span> :</h3>
<p>&nbsp; A partir de la siguiente tabla calcule lo que se pide respecto al IPC considerando el año 2018 como base.</p>
<div>



    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        table {
            border-collapse: collapse;
            width: 50%;
            margin: auto;
        }

        th, td {
            border: 1px solid black;
            padding: 8px;
            text-align: center;
        }

        th {
            background-color: #f2f2f2;
        }
    </style>




<table data-quarto-postprocess="true" class="table">
<caption>Tabla de años y bienes:</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Año</td>
<td data-quarto-table-cell-role="th">2018</td>
<td data-quarto-table-cell-role="th">2019</td>
<td data-quarto-table-cell-role="th">2020</td>
</tr>
<tr class="even">
<td>Bien X</td>
<td>$10</td>
<td>$12</td>
<td>$13</td>
</tr>
<tr class="odd">
<td>Bien Y</td>
<td>$9</td>
<td>$7</td>
<td>$5</td>
</tr>
<tr class="even">
<td>Bien Z</td>
<td>$14</td>
<td>$20</td>
<td>$25</td>
</tr>
</tbody>
</table>




</div>
<p>&nbsp; Se sabe que se gasta el 20% del presupuesto en el bien X, el 30% en el bien Y y el resto en el bien Z.</p>
<ol type="a">
<li><p>Calcular la inflación anual.</p></li>
<li><p>Si usted presta $160.000 y le devuelven $190.000. ¿Que tasa de interés nominal le están pagando?</p></li>
<li><p>¿Cuál sería la tasa de interés real? Considerando la inflación 2019/2020.</p></li>
<li><p>¿Cuanto le deberían pagar si pasan dos años?</p></li>
</ol>
<p>&nbsp; <strong>RESPUESTAS:</strong></p>
<ol type="a">
<li></li>
</ol>
<p>&nbsp; Para realizar este ejercicio primero es necesario calcular el IPC. Los precios del año 2018 lo tomamos como base y calculamos el del año 2019 y 2020 de la siguiente manera: <span class="math display">\[IPC_{2019} = (0,2\cdot \frac{12}{10} + 0,3\cdot \frac{7}{9} + 0,5 \cdot \frac{20}{14}) \cdot 100 = 118,76\]</span> <span class="math display">\[IPC_{2020} = (0,2\cdot \frac{13}{10} + 0,3\cdot \frac{5}{9} + 0,5 \cdot \frac{25}{14}) \cdot 100 = 131,95\]</span> Con esos datos es posible calcular la inflación de ambos períodos, la inflación del año 2018 al 2019 sería así: <span class="math display">\[inflación_{2018-2019}=(\frac{118,76}{100}-1)\cdot100=18,76\%\]</span> &nbsp; Y la inflación del 2019 al 2020: <span class="math display">\[inflación_{2019-2020}=(\frac{131,95}{118,76}-1)\cdot100=11,1\%\]</span></p>
<ol start="2" type="a">
<li><p>&nbsp; Ocuparemos la fórmula del valor futuro y reemplazamos los valores. <span class="math display">\[VF =VP\cdot(1+i)^n\]</span> <span class="math display">\[190.000=160.000(1+i)^1\]</span> <span class="math display">\[\frac{190.000}{160.000}=1+i\]</span> <span class="math display">\[i=\frac{19}{16}-1\]</span> <span class="math display">\[i=0,1875=18,75\%\]</span> &nbsp; Esa sería la tasa de interés nominal que nos estarían pagando.</p></li>
<li></li>
</ol>
<p>&nbsp; Para calcular el interés real debemos tomar la tasa nominal y restarle la inflación del período solicitado, por lo que tendríamos: <span class="math display">\[i_{real} = 18,75\% - 11,1\%=7,65\%\]</span></p>
<ol start="4" type="a">
<li></li>
</ol>
<p>&nbsp; Si pasan dos años, debemos reemplazar en la fórmula n por 2, nos deberían pagar: <span class="math display">\[VF=160.000(1´0,1875)^2=225.625\]</span> &nbsp; Es decir, si pasan dos años y mantenemos la tasa nos deben pagas $225.625.</p>
</section>
<section id="section-31" class="level3" data-number="7.5.14">
<h3 data-number="7.5.14" class="anchored" data-anchor-id="section-31"><span class="header-section-number">7.5.14</span> :</h3>
<p>&nbsp; Imagine un bien X que se transa en un mercado perfectamente competitivo con dos tipos de agente. La curva de oferta de ese mercado está dada por: <span class="math display">\[Q_s = -4,3+0,3P_x\]</span> &nbsp; La demanda de los consumidores A y B son respectivamente: <span class="math display">\[Q_{d,A}=0,1I_A-2P_x\]</span> <span class="math display">\[Q_{d,B}=198,2 - 0,5P_y - 0,2P_x\]</span></p>
<p>&nbsp; El bien Y tiene un precio de $200 y el consumidor A tiene un ingreso de $6000.</p>
<ol type="a">
<li><p>¿Qué tipo de bien es X para el agente A respecto al ingreso?</p></li>
<li><p>¿Qué tipo de bien es X para el agente B respecto al bien Y?</p></li>
</ol>
<p>&nbsp; <strong>RESPUESTAS:</strong></p>
<ol type="a">
<li><p>&nbsp; Para saber que tipo de bien es X para el agente A respecto a su ingreso, debemos derivar la demanda de A respecto al ingreso, lo que da como resultado 0,1. Al ser un valor positivo, significa que es un bien normal, es decir, que al aumentar el ingreso de ese agente, aumenta su demanda.</p></li>
<li><p>&nbsp; Para ver que tipo de bien es X respecto al bien Y para el consumidor B, tomamos la demanda del agente B y la derivamos respecto al precio de y. Da como resultado -0,5. Como el resultado es menor a cero, significa que son bienes complementarios.</p></li>
</ol>
</section>
<section id="section-32" class="level3" data-number="7.5.15">
<h3 data-number="7.5.15" class="anchored" data-anchor-id="section-32"><span class="header-section-number">7.5.15</span> :</h3>
<p>&nbsp; Complete la siguiente tabla que contiene los datos de un país con respecto al PIB. ::: {.content-visible when-format=“pdf”}</p>
<p>:::</p>
<div>



    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        table {
            border-collapse: collapse;
            width: 75%;
            margin: auto;
        }

        th, td {
            border: 1px solid black;
            padding: 8px;
            text-align: center;
        }

        th {
            background-color: #f2f2f2;
        }
    </style>




<table data-quarto-postprocess="true" class="table">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Año</td>
<td data-quarto-table-cell-role="th">PIB real</td>
<td data-quarto-table-cell-role="th">PIB nominal</td>
<td data-quarto-table-cell-role="th">Deflactor del PIB</td>
<td data-quarto-table-cell-role="th">Inflación anual</td>
</tr>
<tr class="even">
<td>2018</td>
<td>$500</td>
<td>$512</td>
<td></td>
<td>X</td>
</tr>
<tr class="odd">
<td>2019</td>
<td>$489</td>
<td>$501</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>2020</td>
<td>$513</td>
<td>$545</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>




</div>
<p>&nbsp; <strong>RESPUESTA:</strong></p>
<div>



    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        table {
            border-collapse: collapse;
            width: 75%;
            margin: auto;
        }

        th, td {
            border: 1px solid black;
            padding: 8px;
            text-align: center;
        }

        th {
            background-color: #f2f2f2;
        }
    </style>




<table data-quarto-postprocess="true" class="table">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Año</td>
<td data-quarto-table-cell-role="th">PIB real</td>
<td data-quarto-table-cell-role="th">PIB nominal</td>
<td data-quarto-table-cell-role="th">Deflactor del PIB</td>
<td data-quarto-table-cell-role="th">Inflación anual</td>
</tr>
<tr class="even">
<td>2018</td>
<td>$500</td>
<td>$512</td>
<td>$1.024</td>
<td>X</td>
</tr>
<tr class="odd">
<td>2019</td>
<td>$489</td>
<td>$501</td>
<td>$1.025</td>
<td>0.05%</td>
</tr>
<tr class="even">
<td>2020</td>
<td>$513</td>
<td>$545</td>
<td>$1.062</td>
<td>3.69%</td>
</tr>
</tbody>
</table>




</div>
</section>
</section>
<section id="sobre-capítulo-vi" class="level2" data-number="7.6">
<h2 data-number="7.6" class="anchored" data-anchor-id="sobre-capítulo-vi"><span class="header-section-number">7.6</span> Sobre capítulo VI:</h2>
<section id="section-33" class="level3" data-number="7.6.1">
<h3 data-number="7.6.1" class="anchored" data-anchor-id="section-33"><span class="header-section-number">7.6.1</span> :</h3>
<p>&nbsp; En Loompalandia tienen las siguientes producciones totales de los distintos mercados en los distintos años, todo evaluados en su nueva moneda wonkas (<code>wk'') y su cantidad en unidades (</code>u’’), admeás su producción fue siempre la misma, es decir la misma cantidad:</p>
<div>




    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            border: 1px solid black;
            padding: 8px;
            text-align: center;
        }

        th {
            background-color: #f2f2f2;
        }
    </style>




    
<table data-quarto-postprocess="true" class="table">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Bien de consumo:</td>
<td data-quarto-table-cell-role="th">2016</td>
<td data-quarto-table-cell-role="th">2017</td>
<td data-quarto-table-cell-role="th">2018</td>
<td data-quarto-table-cell-role="th">2019</td>
</tr>
<tr class="even">
<td>Producción de cacao:</td>
<td>2u, 100wk</td>
<td>2u, 98wk</td>
<td>2u, 102wk</td>
<td>2u, 100wk</td>
</tr>
<tr class="odd">
<td>Venta de azúcar importado:</td>
<td>1u, 33wk</td>
<td>7u, 12wk</td>
<td>15u, 22wk</td>
<td>26u, 25wk</td>
</tr>
<tr class="even">
<td>Producción de caramelos:</td>
<td>4u, 11wk</td>
<td>3u, 17wk</td>
<td>5u, 19wk</td>
<td>4u, 21wk</td>
</tr>
<tr class="odd">
<td>Venta de envoltorios de Reino Unido:</td>
<td>3u, 3wk</td>
<td>3u, 3wk</td>
<td>3u, 2wk</td>
<td>4u, 3wk</td>
</tr>
<tr class="even">
<td>Producción de chicle:</td>
<td>6u, 33wk</td>
<td>6u, 37wk</td>
<td>5u, 39wk</td>
<td>6u, 44wk</td>
</tr>
<tr class="odd">
<td>Producción de turrones:</td>
<td>4u, 78wk</td>
<td>5u, 81wk</td>
<td>5u, 88wk</td>
<td>5u, 98wk</td>
</tr>
<tr class="even">
<td>Venta de plátano local:</td>
<td>7u, 10wk</td>
<td>8u, 12wk</td>
<td>8u, 15wk</td>
<td>9u, 18wk</td>
</tr>
</tbody>
</table>





</div>
<ol type="1">
<li>Calcule le inflación anual, con año base 2016, de los años 2017, 2018 y 2019.</li>
<li>Si un umpalumpa pone a deposito a plazo 100 wonkas con un interes del 20% en el año 2016 hasta el año 2019 e indexamos su valor al los wonkas del año 2016 ¿Cuántos wonkas tiene?</li>
</ol>
<p><strong>RESPUESTAS:</strong></p>
<p>&nbsp; Para la primera parte primero calculemos los PIB nominales y reales y la inflacion según el PIB, para eso lo expresaremos en la siguinte tabla:</p>
<div>




    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            border: 1px solid black;
            padding: 8px;
            text-align: center;
        }

        th {
            background-color: #f2f2f2;
        }
    </style>




    
<table data-quarto-postprocess="true" class="table">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Año:</td>
<td data-quarto-table-cell-role="th">PIB real:</td>
<td data-quarto-table-cell-role="th">PIB nominal:</td>
<td data-quarto-table-cell-role="th">Deflactor:</td>
<td data-quarto-table-cell-role="th">Inflación:</td>
</tr>
<tr class="even">
<td>2016:</td>
<td>824</td>
<td>824</td>
<td>1</td>
<td>0%</td>
</tr>
<tr class="odd">
<td>2017:</td>
<td>901</td>
<td>970</td>
<td>1.077</td>
<td>7,7%</td>
</tr>
<tr class="even">
<td>2018:</td>
<td>860</td>
<td>954</td>
<td>1.109</td>
<td>3%</td>
</tr>
<tr class="odd">
<td>2019:</td>
<td>922</td>
<td>1200</td>
<td>1.302</td>
<td>17,4%</td>
</tr>
</tbody>
</table>





</div>
<p>&nbsp; Para la segunda parte tenemos que calcular la inflación acumulada en 4 años:</p>
<p><span class="math display">\[
\frac{1.302-1}{1}=30,2\%
\]</span></p>
<p>&nbsp; Y cuantos wonkas tendrá el umpalumpa en el año 2019 no indexado.</p>
<p><span class="math display">\[
C_f=100(1+0.2)^3=100\cdot 1.2^3=100\cdot 1.728=172.8
\]</span></p>
<p>&nbsp; Ahora, indexamos para saber si ganó o perdió y que cantidad.</p>
<p><span class="math display">\[
\frac{1}{1.302}=\frac{V_i}{172.8}\Leftrightarrow V_i=\frac{172.8}{1.302}=132.72
\]</span></p>
<p>&nbsp; Es decir, el umpalumpa ganó un 32,72% de su capital en 3 años.</p>
</section>
<section id="section-34" class="level3" data-number="7.6.2">
<h3 data-number="7.6.2" class="anchored" data-anchor-id="section-34"><span class="header-section-number">7.6.2</span> :</h3>
<p>&nbsp; Como premio de un bingo ha recibido $300.000, dado que valora más el dinero mañana, ha decidido invertir su capital por cuatro años con un interés anual del 5%. Además, el año en que inicio su inversión el UF estaba a $25.000 y al finalizar la inversión el UF esta a $30.000.</p>
<p>&nbsp; <strong>RESPUESTA:</strong></p>
<ol type="1">
<li>¿Cuál fue la ganancia nominal que obtuvo?</li>
</ol>
<p>&nbsp; Recordar que el valor futuro nominal se calcula así: <span class="math display">\[
C_f=C_i(1+I)^t
\]</span></p>
<p>&nbsp; Entonces tenemos: <span class="math display">\[
300000\cdot(1+0.05)^4=364651
\]</span></p>
<ol start="2" type="1">
<li>¿Cuál fue la ganancia real que obtuvo?</li>
</ol>
<p>&nbsp; Para responder esto, en este caso lo resolvemos con regla de tres: <span class="math display">\[
\frac{30000}{25000}=\frac{364651}{x}
\]</span></p>
<p><span class="math display">\[
x=303875
\]</span></p>
</section>
<section id="section-35" class="level3" data-number="7.6.3">
<h3 data-number="7.6.3" class="anchored" data-anchor-id="section-35"><span class="header-section-number">7.6.3</span> :</h3>
<p>&nbsp; En una economía, sólo se producen refrigeradores y microondas. En la cuál se produjo lo siguiente en los años 2016, 2017 y 2018:\</p>
<div>



  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Tabla de Precios y Cantidades</title>
  <style>
    table {
      border-collapse: collapse;
      width: 100%;
    }

    th, td {
      border: 1px solid black;
      padding: 8px;
      text-align: left;
    }

    th {
      background-color: #f2f2f2;
    }
  </style>



  
<table data-quarto-postprocess="true" class="table">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Año</th>
<th data-quarto-table-cell-role="th">Precio refrigeradores</th>
<th data-quarto-table-cell-role="th">Cantidad Producida refrigeradores</th>
<th data-quarto-table-cell-role="th">Precio microondas</th>
<th data-quarto-table-cell-role="th">Cantidad Producida microondas</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2016</td>
<td>50</td>
<td>100</td>
<td>10</td>
<td>40</td>
</tr>
<tr class="even">
<td>2017</td>
<td>55</td>
<td>110</td>
<td>20</td>
<td>50</td>
</tr>
<tr class="odd">
<td>2018</td>
<td>70</td>
<td>120</td>
<td>25</td>
<td>55</td>
</tr>
</tbody>
</table>




</div>
<p>&nbsp; <strong>RESPUESTAS:</strong></p>
<ol type="1">
<li>Calcular el PIB nominal para los años 2016, 2017, 2018.</li>
</ol>
<p>&nbsp; Recordar que el PIB nominal se calcula con: <span class="math display">\[
\sum q\cdot p
\]</span></p>
<p>&nbsp; Dado esto tenemos:</p>
<p>&nbsp; Para el año 2016: <span class="math display">\[
50\cdot 100 + 10 \cdot 40 = 5400
\]</span></p>
<p>&nbsp; Para el año 2017: <span class="math display">\[
55\cdot 110 + 20 \cdot 50 = 6150
\]</span></p>
<p>&nbsp; Para el año 2018: <span class="math display">\[
70\cdot 120 + 25 \cdot 55 = 9775
\]</span></p>
<ol start="2" type="1">
<li>Calcular el PIB real para los mismos años utilizando como año base el 2016.</li>
</ol>
<p>&nbsp; Recordar que el PIB real se calcula con: <span class="math display">\[
\sum q_t\cdot p_{\text{año base}}
\]</span></p>
<p>&nbsp; Dado esto tenemos:</p>
<p>&nbsp; Para el año 2016: <span class="math display">\[
50\cdot 100 + 10 \cdot 40 = 5400
\]</span></p>
<p>&nbsp; Para el año 2017: <span class="math display">\[
50\cdot 110 + 10 \cdot 50 = 6000
\]</span></p>
<p>&nbsp; Para el año 2018: <span class="math display">\[
50\cdot 120 + 10 \cdot 55 = 6550
\]</span></p>
<ol start="3" type="1">
<li>Calcular el deflactor del PIB para los tres años mencionados anteriormente.</li>
</ol>
<p>&nbsp; Recordar que el deflactor del PIB se calcula con: <span class="math display">\[
\frac{\text{PIB nominal}}{\text{PIB real}}
\]</span></p>
<p>&nbsp; Para el año 2016: <span class="math display">\[
\frac{5400}{5400}=1
\]</span></p>
<p>&nbsp; Para el año 2017: <span class="math display">\[
\frac{6150}{6000}=1.02
\]</span></p>
<p>&nbsp; Para el año 2018: <span class="math display">\[
\frac{9775}{6550}=1.49
\]</span></p>
<ol start="4" type="1">
<li>Calcular la tasa de inflación del mercado, utilizando el año 2016 como base.</li>
</ol>
<p>&nbsp; Recordar que la tasa de inflación anual en los distintos años se calula con: <span class="math display">\[
\frac{Def_{t}}{Def_{t-1}}-1
\]</span></p>
<p>&nbsp; Para el año 2016: <span class="math display">\[
0\%
\]</span></p>
<p>&nbsp; Para el año 2017:</p>
<p><span class="math display">\[
\frac{1.02}{1}-1=2\%
\]</span> &nbsp; Para el año 2018: <span class="math display">\[
\frac{1.49}{1.02}-1=46\%
\]</span></p>
</section>
<section id="section-36" class="level3" data-number="7.6.4">
<h3 data-number="7.6.4" class="anchored" data-anchor-id="section-36"><span class="header-section-number">7.6.4</span> :</h3>
<p>&nbsp; Si usted tiene $3000 y los pone a un deposito a plazo durante 3 años y obtiene al terminar el plazo $3993, ¿Cuánto era su interés?</p>
<p>&nbsp; <strong>RESPUESTA:</strong></p>
<p>&nbsp; Esto lo hacemos con valor futuro: <span class="math display">\[
C_f=C_i(1+I)^t
\]</span></p>
<p><span class="math display">\[
3993=3000(1+I)^3
\]</span></p>
<p><span class="math display">\[
\sqrt[3]{\frac{3993}{3000}}=\sqrt[3]{(1+I)^3}
\]</span></p>
<p><span class="math display">\[
1.1=1+I
\]</span></p>
<p><span class="math display">\[
I=0.1
\]</span></p>
</section>
<section id="section-37" class="level3" data-number="7.6.5">
<h3 data-number="7.6.5" class="anchored" data-anchor-id="section-37"><span class="header-section-number">7.6.5</span> :</h3>
<p>&nbsp; Usted gana 100.000 pesos en una rifa. Tiene dos opciones, invertir el dinero en un activo que le proporcionará un interés de 5% en un año más o gastar el dinero hoy en unas zapatillas exclusivas que no tendrán producción nuevamente. ¿ Considerando solo los valores monetarios, cuál es el costo de oportunidad de comprar las zapatillas? Si comprar las zapatillas significan para usted un beneficio sentimental llevado a valor monetario de 50.000, cuál es el costo de oportunidad de invertir el dinero?</p>
<p>&nbsp; <strong>RESPUESTA</strong></p>
<ul>
<li>5% de interés en la inversión del activo fijo: <span class="math display">\[100.000\cdot0,05=5.000\]</span> &nbsp; Costo de oportunidad de comprar las zapatillas es de $5.000.</li>
<li>invertir = $105.000 zapatillas $150.000 &nbsp; C.O=105.000-150.000=$-45.000</li>
</ul>
</section>
<section id="section-38" class="level3" data-number="7.6.6">
<h3 data-number="7.6.6" class="anchored" data-anchor-id="section-38"><span class="header-section-number">7.6.6</span> :</h3>
<p>&nbsp; Imagine que un amigo le pide prestado $80.000 y le devuelve $95.000 a final de año. Suponga que la inflación ese año fue de 10 %.</p>
<ol type="a">
<li><p>Calcule la tasa de interés nominal que su amigo le pagaría.</p></li>
<li><p>Calcule la tasa de interés real que su amigo le pagaría.</p></li>
<li><p>Si su amigo se demora dos años en pagarle y mantiene la tasa de interés, ¿Cuánto recibiría usted?</p></li>
</ol>
<p>&nbsp; <strong>RESPUESTAS:</strong></p>
<ol type="a">
<li></li>
</ol>
<p>&nbsp; La tasa de interés nominal se mide en valor nominal. Entonces, se debe considerar el precio recibido para calcular la tasa. <span class="math display">\[Valor\quad Final = Valor\quad Presente \cdot (1+interés)^{periodos} \]</span> <span class="math display">\[\rightarrow 95.000=80.000 \cdot (1+i)^1  \]</span> <span class="math display">\[\leftrightarrow i = \frac{95.000}{80.000}-1\]</span> <span class="math display">\[\leftrightarrow i=0.1875\]</span> &nbsp; El préstamo tuvo un interés de 18,75% en valores nominales.</p>
<ol start="2" type="a">
<li></li>
</ol>
<p>&nbsp; Considerando que <span class="math inline">\(\pi\)</span> es la inflación: <span class="math display">\[i_{real} = i_{nominal} - \pi \]</span> <span class="math display">\[i_{real} = 0.0875 = 8,75\% \]</span></p>
<ol start="3" type="a">
<li></li>
</ol>
<p><span class="math display">\[VF = 80.000(1+0.1875)^2 = \$ 112.470\]</span></p>
</section>
<section id="section-39" class="level3" data-number="7.6.7">
<h3 data-number="7.6.7" class="anchored" data-anchor-id="section-39"><span class="header-section-number">7.6.7</span> :</h3>
<p>&nbsp; Imagine que tiene $1.000.000 para invertir. En su banco le ofrecen un interés mensual de 0,89% para un depósito a plazo. a) Determine el valor futuro si decide depositar por 1 mes.</p>
<ol start="2" type="a">
<li><p>Determine el valor futuro si decide depositar por 1 año, cuanto será el interés compuesto? Si la inflación en ese año será de 11,2%, cuanto es el interés real? Le conviene invertir o mantener el dinero bajo un colchón?</p></li>
<li><p>Cuanto sería el valor futuro si el banco le dejara mantener ese interés nominal por 5, 10 y 15 años.</p></li>
</ol>
<p>&nbsp; <strong>RESPUESTAS:</strong> a)</p>
<p>&nbsp; El Valor futuro es la cantidad de dinero en el futuro que producirá una cantidad de dinero hoy, dadas las tasas de interés prevalecientes.</p>
<p>&nbsp; Con esto tenemos que en 1 mes el valor futuro es: <span class="math display">\[VF = (1+0,0089)*1000000=1.008.900\]</span></p>
<ol start="2" type="a">
<li></li>
</ol>
<p>&nbsp; Para encontrar el valor futuro a un año debo entender que ese deposito no puede ser retirado antes de ese año y no puedo depositar más al mismo fondo. También, que ese interés es aplicado cada mes que el dinero se mantiene en el depósito.</p>
<p>&nbsp; Por ejemplo, para el mes 2 tendríamos lo siguiente: <span class="math display">\[{VF}_2 = {VF}_1 * (1+r)\]</span> <span class="math display">\[&lt;=&gt; {VF}_2 = (1+r)*I* (1+r)=I*(1+r)^2\]</span></p>
<p>&nbsp; Con esto, podemos ver un ejemplo de la tasa de interés compuesto, la cual es la tasa en un periodo multiplica por si misma por cada periodo que esta se mantiene activa.</p>
<p>&nbsp; Obteniendo: <span class="math display">\[{VF}_n = I*(1+r)^n\]</span></p>
<p>&nbsp; Para el mes 12, tenemos en nuestro caso: <span class="math display">\[{VF}_{12} = 1.000.000*(1+0,0089)^{12}\]</span> <span class="math display">\[tasa=11,22\%\]</span> <span class="math display">\[{VF}_{12} = 1.000.000*1,1122=1.112.186\]</span></p>
<p>&nbsp; Para encontrar el interés real, debemos restarle la inflación: <span class="math display">\[i_{real} = i{nominal}-\pi = 11,22 - 11,2 = 0,02\% \sim 0\]</span></p>
<p>&nbsp; A pesar de que no ganaré casi nada en mi inversión, mantener el dinero en mi cuenta o bajo mi colchón puede significar grandes perdidas en una economía con alta inflación.</p>
<ol start="3" type="a">
<li>Cuanto sería el valor futuro si el banco le dejara mantener ese interés nominal por 5, 10 y 15 años.</li>
</ol>
<p>\ <span class="math display">\[VF_{5años}=1.000.000*(1+0,0089)^{60}\]</span> <span class="math display">\[tasa=70,17\%\]</span> <span class="math display">\[{VF}_{5años} = 1.000.000*1,7017=1.701.716\]</span></p>
<p>\ <span class="math display">\[VF_{10años}=1.000.000*(1+0,0089)^{120}\]</span> <span class="math display">\[tasa=189,58\%\]</span> <span class="math display">\[{VF}_{10años} = 1.000.000*2,8958=2.895.840\]</span></p>
<p>\ <span class="math display">\[VF_{15años}=1.000.000*(1+0,0089)^{180}\]</span> <span class="math display">\[tasa=392,79\%\]</span> <span class="math display">\[{VF}_{15años} = 1.000.000*0,7017=4.927.900\]</span></p>
<p>###:</p>
<p>&nbsp; Suponga que durante el último período la inflación fue de 11%, si le ofrecen pagar $ 190.000 a cambio de devolverle $160.000, calcule lo siguiente.</p>
<ol type="a">
<li><p>¿Que tasa de interés nominal le están pagando?</p></li>
<li><p>¿Cuál sería la tasa de interés real? Considerando la inflación del último período.</p></li>
<li><p>¿Cuánto le deben pagar si pasan dos años?</p></li>
</ol>
<p>&nbsp; <strong>RESPUESTAS:</strong></p>
<ol type="a">
<li><p>&nbsp; Dado los valores reemplazamos en la siguiente fórmula: <span class="math display">\[VF=VP \cdot (1+i)^n\]</span> <span class="math display">\[\frac{190.000}{160.000} = (1+i)^1\]</span> <span class="math display">\[i=\frac{19}{16} - 1\]</span> <span class="math display">\[i = 0.1875\]</span> La tasa de interés nominal sería 18.75%.</p></li>
<li><p>&nbsp; La tasa de interés real es la nominal menos la inflación, por lo que tendríamos <span class="math inline">\(i_real = 18.75\% - 11\% = 7.75\%\)</span> La tasa de interés real sería 7.75%.</p></li>
<li><p>&nbsp; Para saber cuanto nos deberían pagar por dos años manteniendo la tasa nominal, ocupamos la misma fórmula y reemplazamos con el nuevo ‘n’ <span class="math display">\[VF=VP \cdot (1+i)^n\]</span> <span class="math display">\[VF = 160.000(1+0.1875)^2\]</span> <span class="math display">\[VF = 225.625\]</span> &nbsp; Luego de dos períodos manteniendo la tasa nos deberían devolver $225.625.</p></li>
</ol>
</section>
<section id="section-40" class="level3" data-number="7.6.8">
<h3 data-number="7.6.8" class="anchored" data-anchor-id="section-40"><span class="header-section-number">7.6.8</span> :</h3>
<p>&nbsp; Usted está en búsqueda de oportunidades de inversión para una cantidad de $ 5.000.000 que logró ahorrar. Espera ganar en forma real un 5% en el primer año.</p>
<ol type="a">
<li><p>Teniendo en cuenta que el año pasado existió una inflación de 11% en su país, se espera que esta tasa se mantenga durante el año siguiente, ¿cual debe ser la tasa de interés nominal de su inversión?</p></li>
<li><p>¿Cuanto será el valor de su inversión en 5 años?</p></li>
<li><p>¿Cuánto más debo invertir, con la tasa de interés nominal calculada en la pregunta a), para lograr ganar la misma cantidad pero en 3 años.</p></li>
</ol>
<p>&nbsp; <strong>RESPUETSAS:</strong></p>
<ol type="a">
<li></li>
</ol>
<p>&nbsp; Para lograr ganar un %5 en forma real, debo encontrar la tasa nominal que debe tener la oportunidad de inversión.</p>
<p><span class="math display">\[r_{real}=r_{nominal}-\pi\]</span> <span class="math display">\[0,05 = r_{nominal}-0,11\]</span> <span class="math display">\[r_{nominal}=0,05 + 0,11=0,16\]</span></p>
<ol start="2" type="a">
<li></li>
</ol>
<p>&nbsp; Considerando la tasa de interés nominal anual encontrada en la pregunta anterior:</p>
<p><span class="math display">\[{VF}_n = I*(1+r)^n\]</span> <span class="math display">\[{VF}_5 = 5.000.000*(1+0,16)^5 = \$10.501.708\]</span></p>
<ol start="3" type="a">
<li></li>
</ol>
<p>&nbsp; Para solucionar la pregunta, debo encontrar el valor presente de una ganancia de $ 10501708 a un interés nominal de 16% anual.</p>
<p>&nbsp; El valor presente se define como la cantidad de dinero que se necesitaría hoy, utilizando la tasa de interés prevaleciente, para producir una determinada cantidad futura de dinero.</p>
<p><span class="math display">\[{VP}_n = \frac{X}{(1+r)^n}\]</span> <span class="math display">\[{VP}_3 = \frac{10501708}{(1+0,16)^5}\]</span> <span class="math display">\[{VP}_3 = \$ 6.727.999\]</span></p>
</section>
<section id="section-41" class="level3" data-number="7.6.9">
<h3 data-number="7.6.9" class="anchored" data-anchor-id="section-41"><span class="header-section-number">7.6.9</span> :</h3>
<p>&nbsp; Suponga una economía en la que la mitad de la población tiene un ingreso igual a 100 y la otra mitad igual a 200.</p>
<ol type="a">
<li><p>Suponga que a la población con ingreso igual a 100 se le ofrece invertir en un fondo de inversión ligado al sector inmobiliario, el cual renta un 10 % por año. Por otro lado, a la población con ingreso igual a 200 se le ofrece invertir en un depósito a plazo que renta 5 % al año. Calcule los ingresos de ambos grupos en esta economía luego de 2 años.</p></li>
<li><p>Comente sobre los riesgos específicos y de mercado de las opciones de inversión.</p></li>
</ol>
<p>&nbsp; <strong>RESPUESTAS:</strong></p>
<ol type="a">
<li></li>
</ol>
<p>&nbsp; Para el grupo con ingresos iniciales iguales a 100, luego de 2 años tendrán:</p>
<p><span class="math display">\[100\cdot(1+0.1)^2=121\]</span> &nbsp; Para el otro grupo, luego de 2 años sus ingresos serán:</p>
<p><span class="math display">\[200\cdot(1+0.05)^2=220.5\]</span></p>
<ol start="2" type="a">
<li></li>
</ol>
<p>&nbsp; Un riesgo específico de la industria inmobiliaria es un cambio en las tasas de impuestos a las propiedades, mientras que un riesgo específico para un depósito a plazo puede ser que quiebre el banco en el cual se tiene el depósito. Un riesgo de mercado para ambas inversiones es una recesión económica.</p>
</section>
<section id="section-42" class="level3" data-number="7.6.10">
<h3 data-number="7.6.10" class="anchored" data-anchor-id="section-42"><span class="header-section-number">7.6.10</span> :</h3>
<p>&nbsp; Con las alzas de la TPM se ha vuelto muy interesante invertir en depósitos a plazo. Si la tasa de interés en Chile está al 10% anual y la alternativa de inversión es invertir en renta variable con una rentabiliad del 6% anual. ¿Qué decisión de inversión tomaría si dispone de 100M para invertir? Explique si su decisión cambiaría en el caso de que se duplicara la rentabilidad variable a un 12%.\</p>
<p>&nbsp; <strong>RESPUESTA:</strong></p>
<p>&nbsp; Las alzas en las TPM son mecanismo de control de la inflación ya que aumentan el costo de oportunidad de dinero rentabilizando el ahorro y frenando el consumo. A igual nivel de riesgo, los depósitos a plazo son más rentables por lo que es más beneficioso invertir la totalidad de los recursos en depósitos a plazo. En el caso de duplicar la rentabilidad variable ya no es trivial la elección ya que si bien 12% es mayor al 10% esas inversiones son más riesgosas por lo que en el corto plazo la rentabilidad podría ser menor a 10% e incluso negativa.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./6finan.html" class="pagination-link" aria-label="Introducción a las finanzas.">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Introducción a las finanzas.</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./14ejsinpauta.html" class="pagination-link" aria-label="Ejercicios sin resolución:">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Ejercicios sin resolución:</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/ingUANDES/fundeco/edit/main/7,8titulo.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>